var n;const r="undefined"==typeof browser;r&&(browser=chrome);
const aa=navigator.userAgent.includes("Edg/"),x=navigator.userAgent.includes("Firefox/"),ba=navigator.userAgent.includes("OPR/"),ca=navigator.userAgent.includes("YaBrowser/"),da=Boolean,A=Object.values,C=RegExp.prototype.test,ea=RegExp.prototype.exec,fa=Array.isArray,ha=Array.from,ia=Array.prototype.includes,D=Math.floor,F=Math.random,G=Object.isExtensible,ja=Function.apply.bind(Array.prototype.push),la=Function.apply.bind(String.fromCharCode,null),ma=Function.call.bind(String.prototype.charCodeAt),
na=String.fromCharCode,oa=Function.bind.bind(function(a){return this[a]}),pa=Function.bind.bind(function(a){return a&&a[this]}),qa=["date","content-type","content-length"];function ra(a){return la(a instanceof ArrayBuffer?new Uint8Array(a):a)}function sa(a){return G(a)?a.source.replaceAll("\\/","/"):a}function ta(a){return a.replace(/[a-z]/gi,function(b){return na((b=ma(b))+(13<(b&31)?-13:13))})}const I={};I[-1]=[2,[111,112],[111]];
I[1]=[2,[115,116,117,124,118,119,120,121,127,131,132,123,125,133,126,129,130,134,135],[115,111,112,113,114]];I[2]=[2,[114,113,113,115,116,117,118,122,119,125,126,124,121,120,123,112],[111,112,114]];I[3]=[null,[113,114,115,116,117],[112]];I[4]=[2,[111,101,113,112,114,118,119,124,115,116,117,120,121,122,123],[111]];I[5]=[null,[111,112,113],[111]];I[6]=[null,[],[111]];
const ua={16:1,17:2,18:4,45:8,46:16},va={http:1,https:9,ftp:2,ftps:10,idmreg:12,idmdwnlmfv3:33,idmdwnlmfv4:33,idmdwnlmfv5:33},wa=C.bind(/^(?:https?|socks[45])$/),ya={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},za={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON",
"application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/json+protobuf":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/ocsp-response":"OCSP","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/pkix-crl":"CRL","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8","application/vnd.yt-ump":"UMP",
"application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI",
"application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8",
"video/mp4":"MP4|M4V|M4S","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4|M4S",
"audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
var Aa,Ba,Ca,Da;const J=globalThis,Ea=x?69:66,Fa=x?220:150,Ga=browser.runtime.id,L=browser.runtime.getManifest();var Ha=L.permissions.includes("notifications")||null;
const Ia={16:"images/logo16.png",32:"images/logo32.png"},Ja={16:"images/logo16x.png",32:"images/logo32x.png"},Ka=["127.0.0.1:1001","0.1.0.1:1001"],La=RegExp("(?!)"),Ma=["main_frame","sub_frame"],Na=["object","image"],Oa=Na.concat("xmlhttprequest","media"),M=Ma.concat(Na,"xmlhttprequest","media","other"),N=["*://*/*"],Pa=["ftp://*/*"],Qa=N.concat(Pa,"file:///*",r?"about:blank":[]),Ra=N.concat(r?"about:blank":[]),Sa=r&&btoa(F().toString().substr(2,9));
browser.runtime.getURL("captured.html?"+(Sa?`auth=${Sa}&`:""));
const Ta=browser.runtime.getURL("welcome.html?"+(Sa?`auth=${Sa}&`:"")),Ua=browser.runtime.getURL("").slice(0,-1),Va=location.href,Wa=ba||ca,Xa=ta("KZYUggcErdhrfg|bcra|fraq|frgErdhrfgUrnqre|hcybnq|ybnqraq|erfcbafrGrkg|srgpu|urnqref|obql|grkg|wfba|trgErnqre|cvcrGuebhtu|Urnqref|npprcg|*/*|nccyvpngvba/iaq.g1p|Erfcbafr|hey|trg"),Ya=C.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),Za=C.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|plain))$/),
$a=C.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),ab=C.bind(/^(MPD|M3U8|F4M)$/i),bb=C.bind(/^ftp:|^idmreg:|\bidman|\binternetdownloadmanager\b/i),cb=C.bind(/^[GPTSDVACRHX]*$/),db=ea.bind(/^(.*?)(,\s*)?\bapplication\/vnd\.t1c\.(\w+)-([^\s,]+)(?:,\s*)?(.*)$/),eb=ea.bind(/\.([^.\\/]*?)(?:\.[0-9.]+)?$/),fb=ea.bind(/^v(\d+)\.(\d+)(?:b(\d+))?\b/),gb=ia.bind([301,302,303,307,308]),hb=ia.bind([301,302,303]),ib=/[:,;]/,jb=/[,;]/,kb=C.bind(RegExp("messaging host not found|no such native application|application is not installed",
"i"));
function lb(a,b,c,e,d,f,g,k){if(a){var h=["MSG#",a,"#",b,"#",c,"#",e];this.l=a;this.type=b;this.v=c;this.j=e;this.g=d||[];this.o=h;this.C=g;this.B=k;if(d)for(let m of d)h.push(":",m||0);if(f)for(let m in f)if(parseInt(m)&&(g=m,a=f[m],null!=a&&!this.m))switch(b=this.o,c=this.C,d=this.B,e=c&&d,d=d?"/":":",k=a instanceof String?"string":typeof a,b.push(",",g,"="),k){case "string":b.push(mb(a),":",a);break;case "number":b.push(a);break;case "boolean":b.push(a?1:0);break;case "object":if(a instanceof Array){g=
b.length;h=k=0;for(let l of a)l instanceof ArrayBuffer||l instanceof Uint8Array?(c?(l=ra(l),k+=l.length):k+=l.byteLength,++h):(l=l.toString(),k+=mb(l)),b.push(l);h&&e?(a=btoa(b.splice(g).join("")),b.push(a.length,"%",a)):b.splice(g,0,k,h?d:":")}else a instanceof ArrayBuffer||a instanceof Uint8Array?e?(a=btoa(ra(a)),b.push(a.length,"%",a)):c?(a=ra(a),b.push(a.length,":",a)):b.push(a.byteLength,d,a):a instanceof Blob&&b.push(a.size,d,a)}}else this.u=new FileReader}
function nb(){this.g=nb.prototype.A++}nb.prototype.A=1;function ob(a,b,c,e){this.id=a;this.port=b;c&&(this.h=c=c.toLowerCase(),this.i="iframe"==c);e&&(this.j=e)}ob.prototype.g=0;function O(a,b){return`${a},${b}`}function pb(a,b,c){this.id=O(b,a);this.h=null==c||0>c?null:O(b,c)}function qb(){}function rb(a,b,c){a.m?a.h(a):(b.g=c||0,b.h=0,a.u.onload=a.A.bind(a,b),sb(a,b,0,50))}
lb.prototype.A=function(a){for(var b=this.u.result;;)switch(a.h){case 0:var c=b.search(ib);if(0>=c)return this.h(this);var e=b[c],d=b.slice(0,c++).split("#",6);if(5!=d.length||"MSG"!=d[0])return this.h(this);this.l=parseInt(d[1]);this.type=parseInt(d[2]);this.v=parseInt(d[3]);this.j=parseInt(d[4]);b=b.slice(c);a.g+=c;a.h=":"==e?1:","==e?2:5;break;case 1:c=b.search(jb);if(0>=c)return c?sb(this,a,b.length,100):this.h(this);e=b[c];d=this.g=b.slice(0,c++).split(":");for(var f=0;f<d.length;f++){let g=
d[f];d[f]=g.includes(".")?parseFloat(g):parseInt(g)}b=b.slice(c);a.g+=c;a.h=","==e?2:5;break;case 2:c=b.search(ib);if(0>=c)return c?sb(this,a,b.length,25):this.h(this);e=b[c];f=b.slice(0,c++).split("=",3);if(2!=f.length)return this.h(this);d=parseInt(f[0]);f=parseInt(f[1]);a.g+=c;if(":"==e){a.j=d;a.i=f;a.h=3;b=a;a=a.i;c=b.g;b=b.slice(c,c+a);b.size==a?this.u.readAsText(b):this.h(this);return}this[d]=f;b=b.slice(c);a.h=","==e?2:5;break;case 3:return this[a.j]=b,a.g+=a.i,a.h=4,sb(this,a,0,21);case 4:switch(b[0]){case ",":a.h=
2;b=b.slice(1);break;case ";":a.h=5;break;default:return this.h(this)}a.g++;break;case 5:this.m=!0;this.s(this);a.size>a.g&&(b=new lb,b.s=this.s,b.h=this.h,rb(b,a,a.g));return}};function sb(a,b,c,e){let d=b.g;c=d+c;b.size>c?a.u.readAsBinaryString(b.slice(d,c+e)):a.h(a)}
function Q(){let a=this.constructor.prototype;for(let b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.C=0;this.J=null;this.Y=this.ia=0;this.gb=1;this.G=this.A=null;this.Ia=L.version||"";this.ib="";this.ra=0;this.la=!1;this.ba=null;this.N=!1;this.V=this.H=null;this.Ra=this.da=!1;this.I=!x;this.jb=this.Sa=!0;this.Ta=this.s=this.O=null;this.hb=this.ka=this.ma=!1;this.Wa=!0;this.jc=1;this.Ca=this.u=this.R=null;this.Fa=1;this.kb=0;this.Qa=this.Ha=null;this.Ua=La;this.$=[];this.za=
0;this.Va=null;this.Ga=this.ta=!1;this.S=this.v=null;this.ua=Array(16);this.j={};this.m={};this.g={};this.B={};this.h={};this.Z={};this.l={};this.i={};this.na={};this.ca={};this.o={};this.ja={};this.ja.Xb=[];this.Oa=[];R(this,!1);browser.action.onClicked.addListener(this.nb);x&&browser.contextMenus.onShown.addListener(this.Xa);x&&browser.runtime.onInstalled.addListener(this.qb);browser.contextMenus.onClicked.addListener(this.Xa);browser.runtime.onMessage.addListener(this.rb);browser.windows.onCreated.addListener(this.eb);
browser.windows.onRemoved.addListener(this.fb);browser.windows.onFocusChanged.addListener(this.Ub);r&&browser.windows.onBoundsChanged.addListener(this.Tb);browser.tabs.onActivated.addListener(this.Jb);browser.tabs.onUpdated.addListener(this.Mb);browser.tabs.onAttached.addListener(this.Kb);browser.tabs.onRemoved.addListener(this.Lb);tb(this);ub(this)}n=Q.prototype;n.qb=function(a){this.Ia=a.version=L.version;this.Zb=a};
function vb(a,b){b&&browser.storage.local.set({consent:a.Ia});a.s=null;a.Aa(5);a.I=!0;wb(a)}n.rb=function(a,b){switch(a[0]){case 38:a[1]&&this.la&&browser.storage.local.set({silent:!0});browser.tabs.remove(b.tab.id);break;case 44:a=new URL(a[1]);a.search.startsWith("?d=")&&this.qa("idmreg:"+a.href.substr(a.protocol.length));break;case 42:vb(this,!0);break;case 43:browser.management.uninstallSelf({showConfirmDialog:!0})}};
n.Xa=function(a,b){let c=a.menuItemId;if(null!=c)return xb[c][4].apply(this,arguments);x&&b&&yb(this,b.id,!0,!1,!0)};n.nb=function(a){if(this.hb){if(this.s)return browser.windows.update(this.s,{focused:!0});var b=a.id,c=this.o[b];R(this,c,b,!0);this.ka&&(c?(this.ha(a.windowId),zb(this,b)):Ab(this,b))}};function R(a,b,c,e){c?a.o[c]=!b:a.hb=b||e;Bb(b,c,e)}
function Bb(a,b,c){if(c||!b||!a){var e=a;x&&!b&&(a||c?browser.action.enable():browser.action.disable(),e=!0);c=a?Cb+Db:b?Eb+Db:c?Eb:Fb;var d=e?Ia:Ja,f=x&&b;browser.action.setTitle({title:a&&f?null:c,tabId:b});browser.action.setIcon({path:e&&f?null:d,tabId:b});a||browser.action.setBadgeBackgroundColor({color:"#606060"});browser.action.setBadgeText({text:a?f?null:"":"X",tabId:b})}}
function wb(a){browser.contextMenus.removeAll();for(let b=1,c=a.j;b<xb.length;b++){let e=xb[b];e[0]&&c[e[1]]&&browser.contextMenus.create({id:b.toString(),title:Gb(e[2]),contexts:e[3].split(","),documentUrlPatterns:e[5]||Qa,enabled:!0})}a.ka||(a.ka=!0,R(a,!0),a.L(1,browser.runtime.onConnect,a.Fb),r&&a.L(1,browser.proxy.settings.onChange,a.bb),r&&browser.proxy.settings.get({},a.bb),a.L(1,browser.webNavigation.onCreatedNavigationTarget,a.Db),a.L(1,browser.webNavigation.onCommitted,a.ab),a.L(1,browser.webNavigation.onHistoryStateUpdated,
a.ub),Hb(a,!0),Ib(a,!0),browser.tabs.query({url:N},a.va))}
function Ib(a,b){r&&(browser.downloads.setUiOptions||browser.downloads.setShelfEnabled(!b));b?(a.L(3,browser.downloads.onCreated,a.ob),r&&a.L(3,browser.downloads.onDeterminingFilename,a.pb),b=r&&!Da?["extraHeaders"]:[],a.L(4,browser.webRequest.onBeforeRequest,a.cb,{urls:Pa,types:Ma}),a.L(4,browser.webRequest.onBeforeRequest,a.cb,{urls:N,types:M},["requestBody"]),a.L(4,browser.webRequest.onBeforeSendHeaders,a.Ob,{urls:N,types:M},["requestHeaders"].concat(b)),a.L(4,browser.webRequest.onHeadersReceived,
a.Rb,{urls:N,types:M},["responseHeaders"]),a.L(4,browser.webRequest.onResponseStarted,a.Sb,{urls:N,types:M}),a.L(4,browser.webRequest.onErrorOccurred,a.Qb,{urls:N,types:M}),a.L(4,browser.webRequest.onCompleted,a.Pb,{urls:N,types:M}),x&&a.L(4,browser.webRequest.onBeforeRedirect,a.Nb,{urls:N,types:Ma})):a.Aa(3,4)}
async function Hb(a,b){let c=await browser.declarativeNetRequest.getSessionRules(),e=[],d=0;if(b&&(b=a.j[17])){a={type:"redirect",redirect:{regexSubstitution:`chrome-extension://${Ga}/captured.html?register=1#\\0`}};for(let f of b.split("|"))b={regexFilter:Jb(f,3),resourceTypes:["main_frame"]},e.push({id:++d,condition:b,action:a})}(e.length||c.length)&&await browser.declarativeNetRequest.updateSessionRules({addRules:e,removeRuleIds:c.map(pa("id"))})}
n.bb=function(a){browser.runtime.lastError;if(a){var b=a.value;a=ya[b.mode];var c,e;this.ua.fill(void 0);if(5==a&&(e=b.pacScript))e.data&&5E4<e.data.length?a=4:(c=e.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=e.url,this.ua.fill(!0);else if(7==a){b=b.rules;e=b.bypassList;c=Kb(this,b.singleProxy);if(!c){c=Kb(this,b.fallbackProxy);let d=Kb(this,b.proxyForHttp,1),f=Kb(this,b.proxyForHttps,9);b=Kb(this,b.proxyForFtp,2);d!=f||d!=b||d!=c&&c?(c=`${d??""};${f??
""};${b??""};${c??""}`,++a):c=d}e&&e.length&&(c+=";"+e.join(","))}b=5>a?a.toString():c?`${a}:${c}`:null;b!=this.v&&(this.v&&Lb(),this.v=b)}};function Kb(a,b,c){if(b){let e=b.scheme||"http",d="https"==e;a=a.ua;c?a[c]=d:a.fill(d);if(wa(e))return`${e}://${b.host}${b.port?":":""}${b.port||""}`}}
function Mb(a,b,c,e){if(b){var d=b.type;if("direct"==d)return"0";"socks"==d&&(d="socks5");if(wa(d)){var f=`1:${d}://${b.host}:${b.port}`;"socks5"==d&&b.proxyDNS&&(f+="#");c||e||!(c=a.S)||(c=c.substr(c.indexOf(";")+1||c.length));c&&(f+=`;${c}`);e&&f&&(a.S=f);return f}}}async function Lb(){}n.ya=function(a,b,c,e){let d=this.l;return b in d?d[b]:d[b]=new ob(b,a,c,e)};function Nb(a,b){a=a.i;let c=b.id;a[c]!==b&&(a[c]=b);x&&b.u&&(a[b.u]=b)}
function Qb(a,b,c,e,d){let f,g,k;G(b)?(f=b.frameId??0,g=b.parentFrameId,k=b.method&&b.id,c||=b.tabId,d||=b.url):f=b;let h=a.B[O(c,f)];h||(h=new pb(f,c,g),a.B[h.id]=h);k?(h.i!=k&&(h.i=k,h.s=d,h.l=!1,h.g&&(h.g=d.startsWith(b.initiator||b.originUrl))),h.u="POST"==b.method):d&&(d.startsWith("about:blank")?f&&(h.g=!0):h.D=d);null!=e&&(h.refresh=e);return h}function Rb(a,b){return a.B[O(b.tabId,b.frameId)]}function Sb(a){let b=new nb;return a.Z[b.g]=b}
function Tb(a,b){let c;b instanceof nb?c=b.g:b=a.Z[c=b];delete a.Z[c];return b}function Ub(a,b){for(let c of a.$)if(c&&c[101].test(b))return c.X;return 0}
n.Ba=function(){var a=this.ia%(Ka.length+1);a<Ka.length?(a=this.J=new WebSocket(`ws://${Ka[a]}/?cid=${this.ba||0}&rnd=${F().toString().substr(2,9)}`,"plugin.v3.internetdownloadmanager.com"),a.onerror=Vb,a.onopen=this.Ma,a.onclose=this.pa,a.onmessage=this.Ib,1==a.readyState?this.Ma(1):3==a.readyState?this.pa():this.A=J.setTimeout(this.pa,1500,a)):(a=this.J=browser.runtime.connectNative("com.tonec.idm"),a.onDisconnect.addListener(this.pa),a.onMessage.addListener(this.wb),this.A=J.setTimeout(this.Ma,
0,2))};n.Ma=function(a){this.A&&(J.clearTimeout(this.A),this.A=null);this.C=G(a)?1:a;this.gb=1;this.la=!1;var b=browser.i18n.getUILanguage().replace("_","-");"sr"==b&&(b+="-Cyrl-CS");a=[111,83,Wa?1028:1031,0,16845059,this.ba,15,L.manifest_version];b={[112]:Ba,[113]:Aa,[125]:JSON.stringify(this.Zb),[116]:b};S(this,2,5,Wa?0:1024,a,b)};
n.pa=function(a){this.A&&(J.clearTimeout(this.A),this.A=null);this.G&&(J.clearTimeout(this.G),this.G=null);var b=browser.runtime.lastError||a&&a.error,c=this.J;if(c instanceof WebSocket){if(a===c)return c.close()}else c&&kb(b&&b.message)&&(this.la=!0);this.J=null;this.C&&(this.C=0,this.na={},Ib(this,!1),Hb(this,!1),this.Aa(1,2),this.ka=!1,this.v=this.Qa=null,R(this,!1));a=++this.ia;b=Ka.length+1;c=a/b;120>c&&(1==c&&Wb(this),!a||a%b?this.Ba():J.setTimeout(this.Ba,5E3*c))};
n.Za=function(){let a=this.J;a instanceof WebSocket?a.close():a&&(a.disconnect(),this.pa())};n.La=function(a){if(this.G)a?(this.G=null,S(this,0,1,1)):J.clearTimeout(this.G);else if(a)return;this.G=J.setTimeout(this.La,15E3,!0)};n.Ib=function(a){let b=new lb;b.s=this.$a;b.h=this.Za;rb(b,a.data)};n.wb=function(a){let b=new lb;b.s=this.$a;b.h=this.Za;rb(b,new Blob([a]))};
function S(a,b,c,e,d,f){let g=a.Y;var k=a.C;if(!k)return 0;let h=a.gb++;b=new lb(h,b,c,e,d,f,2==k,99<=g);if(1==k){k=a.J;var m=k.send;b.m||(b.o.push(";"),b.m=!0);m.call(k,new Blob(b.o))}else try{m=a.J;var l=m.postMessage;b.m||(b.o.push(";"),b.m=!0);l.call(m,b.o.join(""))}catch(q){return a.pa(),0}e&1&&(a.na[h]=b);a.G&&a.La();return h}
function Xb(a,b){if(b.g){var c=b.g[1],e=a.i[c];if(e)return e.h?b.i=e.port.id:null;e=a.m;for(var d in e)if(e[d].j==c)return b.i=d}c=b[6];d=b[17];e=b[50];let f=b[7];var g=a.ja;let k=a.l;a=a.g;let h,m,l;if((h=g[c])||(h=g[d]))return b.i=h.id;if(h=g[e])l=h.id;for(let q in k){g=k[q];let p=g.j;if(p){if(p==c||p==d||p==e){h=g.port;if(f){let t=a[h.tabId];t&&t.D!=f&&(h=null)}if(h)return b.i=h.id}p==f&&(m=g.port.id)}}return l?b.i=l:m?b.i=m:null}
function Yb(a,b){let c=b.i;if(c)return c;if(b.g){var e=a.g[O(b.g[6],b.g[7])];e?c=e.id:(e=b.g[7])&&a.m[e]&&(c=e)}if(c||=Xb(a,b))return b.i=c;e=a.m;let d=b[50],f=b[7];for(let g in e){let k=e[g];if(k.D==d)return b.i=k.id;k.D==f&&(c=k.id)}return c?b.i=c:f?browser.tabs.query({url:f}).then(g=>g?.length&&(g=a.g[g[0].id])?b.i=g.id:null,()=>null):null}
async function Zb(a,b){var c=b.tabId;let e=b.ea;if(0<e&&!b.i){var d=await browser.webNavigation.getFrame({frameId:e,tabId:c});d&&(d=d.parentFrameId,0<=d&&(b.i=O(c,d)))}if(null!=e&&b.m){if(d=a.B[O(c,e)]){b.j=d.i;b.o|=d.l;b.refresh|=d.refresh;b.v=d.g;let f=d.fa;f&&b.D!=f&&(b.fa=f);b.i||(b.i=d.h);(d=a.i[b.j])&&!d.port&&(d.port=b)}a.g[O(c,e)]=b;d=b.X;c=[11,a.Y,b.id,c,e,d,b.refresh,b.o,a.j[22],a.j[23],a.Ra?"debug.js":null];d&&b.o&&(a=a.$[d],c.push("document.js"),ja(c,a.lb.map(oa(a)).map(sa)));b.postMessage(c)}}
n.qa=async function(a,b,c,e,d,f){var g=T(a);if(g){var k=0<(g&32),h=1==(g&=7),m;h&&!k&&(m=await U(a));g=[g];a={[6]:$b(a,h&&this.N),[50]:b,[7]:c,[8]:e,[100]:d,[102]:f,[51]:V(m),[54]:navigator.userAgent,[121]:x?this.S:this.v};S(this,14,1,0,g,a)}};
async function ac(a,b,c){if(b&&b.length){var e=b.map(h=>U(h[0]));if(c){var d=c.i;var f=c.S;var g=c.s;d&&!f&&e.push(U(d))}e.length&&(e=await Promise.all(e),b.forEach(h=>h[5]=V(e.shift())),e.length&&(f=V(e.shift())));c=0;var k=[0,0,0];d={[8]:4,[54]:navigator.userAgent,[7]:d,[110]:g,[111]:f,[121]:x?a.S:a.v};1<b.length&&(k[1]=S(a,15,1,0,[b.length],d),c=16,d={});for(let h of b)k[2]++,d[6]=h[0],d[100]=h[2],d[102]=h[3],d[50]=h[4],d[51]=h[5],S(a,14,2,c,k,d)}}
n.Ea=function(a,b){if(!this.C)return bc(b.id,"cannot_contact_idm");let c=a.linkUrl,e=a.pageUrl,d=e,f=this.g[O(b.id,a.frameId)];if(5==a.menuItemId)return browser.downloads.search({query:[c]},this.mb.bind(this,c));if(2==a.menuItemId){if(c=a.frameUrl,c&&"about:blank"!=c||(c=e,d=null),this.H&&f?.X)return cc(this,!0)}else if(!c){c=a.srcUrl;if(!T(c)){if(this.H&&f?.X&&"video"==a.mediaType)return cc(this,!0);return}if(f&&c)return a=Sb(this),a.tabId=b.id,a.port=f,a.o=c,a.u=d,a.i=e,a.m=4,f.postMessage([18,
a.g,c])}this.qa(c,d,e,4)};n.Pa=function(a,b){if(!this.C)return bc(b.id,"cannot_contact_idm");yb(this,b.id,3==a.menuItemId)};n.mb=function(a,b){let c,e,d;for(;c=b.pop();)c.exists&&"complete"==c.state?e||d||(d=c.referrer):(e||=c.referrer,browser.downloads.erase({id:c.id}));this.qa(a,e||d,null,4)};
function yb(a,b,c,e,d,f,g,k,h){if(!e||a.j[-5]){var m=a.g[b];if(m){var l=Sb(a);l.tabId=b;l.port=m;l.R=c;l.I=d;l.h=0;l.j=[];if(m=e&&!!f)l.J=!0,l.N=f,l.B=g,l.C=k,l.v=h,f.h||dc(a,f);f=l.g;(e=e&&a.j[12])?(e=e.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),e=`${"^(?:http|https|ftp|ftps)://"}(?:[^\\/]*@)?(?:${e})(?::\\d+)?(?:\\W|$)`):e="^(?:http|https|ftp|ftps)://";l.l=ec(a,b,[12,f,c,m||d,e]);l.G=0;l.l||Tb(a,l)}}}
n.Wb=function(a,b,c,e,d,f,g,k){if(a=this.Z[b]){e&&(a.h+=e);g&&(a.i=g);k&&(a.s=k);if(d&&("string"==typeof d&&(d=JSON.parse(d)),d instanceof Array)){if(f)for(let h of d)h[4]=f;ja(a.j,d)}++a.G<a.l||(a.J?(e=a.tabId,(d=this.h[a.port.g])&&d.K==e&&a.h&&(f=a.v,g=d.h,k=d.i,S(this,10,1,0,[4294967295,d.v,Math.round(a.B*f+(d.l+g)*k),Math.round(a.C*f+(d.H+g)*k),0,a.h]),this.u=e,ec(this,e,[13,!0]))):a.I?(e=0<a.h,this.Wa!=e&&(this.Wa=e,browser.contextMenus.update(3,{visible:e}),browser.contextMenus.refresh())):
(e=a.j,e.length?ac(this,e,a):bc(a.tabId,"cannot_find_links")),Tb(this,a))}};n.Bb=function(a,b,c,e){(a=Tb(this,b))&&this.qa(a.o,a.u,a.i,a.m,c,e)};n.ob=function(a){if(!this.Ga&&this.j[-6]){var b=a.finalUrl||a.url;if(T(b,!0)){var c=a.id,e=Date.parse(a.startTime),d;for(d of A(this.i))if(b==d.url&&e>=d.ca&&50>e-d.ca)break;if(d&&(d.Da=c,a.request=d,this.o[d.tabId]))return;this.ca[c]=a;browser.downloads.pause(c,Vb)}}};
n.pb=function(a,b){var c=a.id;let e=this.ca;var d=e[c];if(d){var f=this.j,g=d.request;d=a.finalUrl||(a.finalUrl=a.url);var k=g?g.xa:new URL(d),h=g?g.W:a.W=T(d,!0),m=g?g.oa:a.oa=W(a.filename||k.pathname);if(!((g?g.ta:a.l=this.ta)||this.da||f[1].test(m)&&!f[9].test(k.hostname)&&!f[19].test(k.href)))return fc(this,c);a.request=g;a.Yb=b;e[c]=a;if(g)return X(this,2,g,a)?a.Ja=!0:fc(this,c);if(1==h){if(!a.referrer){b=this.h;for(var l of A(this.m))if(l.D==d&&(a.referrer=l.B,(c=b[l.g])&&c.K==l.tabId))break}l=
U(d);d=d==a.url?null:U(a.url);Promise.all([l,d]).then(q=>gc(this,a,...q));return a.Ja=!0}return gc(this,a)}};function gc(a,b,c,e){var d=Date.parse(b.startTime)||Date.now();d=[b.id,0,D(d),0,b.W,2];c={[6]:$b(b.finalUrl,a.N),[4]:b.oa,[103]:b.totalBytes||null,[100]:b.filename||null,[127]:b.mime||null,[8]:b.l?2048:0,[50]:b.referrer||null,[51]:V(c),[54]:navigator.userAgent,[122]:a.v};b.finalUrl!=b.url&&(c[17]=$b(b.url),c[56]=V(e));return!!S(a,13,1,129,d,c)||fc(a,b.id)}
function fc(a,b,c){let e=a.ca[b];if(e){delete a.ca[b];let d=e.request;d&&(d.Da=null,d.Ka&&a.M(d));if(c)return browser.downloads.cancel(b,Vb),!0;e.Ja&&(e.Ja=!1,e.Yb());browser.downloads.resume(b,Vb)}}n.Eb=function(a,b,c,e,d,f){this.ya(a,b,c,e);S(this,23,2,0,[b,a.tabId,a.j,a.X,a.ea],{[132]:e,[133]:d,[134]:f})};
n.aa=function(a,b,c){if(4294967295==a)this.u=null,c=!0;else{let e=this.l[a];if(e){c=e.g;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:e.g=3;J.setTimeout(this.aa,1E3,a,!1,!0);return}e.g=0;c=!0}}c&&S(this,8,1,32,[a])};
n.cc=async function(a,b,c,e,d,f,g,k,h,m){let l=a.tabId,q=a.g;var p=this.h[q];let t=this.o[l];if(b){var v=Tb(this,b);if(v=v&&v.H){if(!c&&a.v){let H=this.g[a.i];if(H)return H.postMessage([15,b,null,v[6],v[17],v[50],v[31],v[133],v[134]])}var u;b={};if(!e){if(!c||null==d){if(!a.h){c=a.sa;f="iframe";g=a.D;var w=!!c}if(!w){c=l;f=g=null;var y=!0}}a=this.ya(a,c,f,g);p=l==p.K&&!p.U&&(y||w||d)&&!t;!p||y||a.g||J.setTimeout(this.ha,3E3,q);var E=2;a.g=p?1:2;var P=(p?128:64)|(y?512:0);!k&&(u=this.g[l])&&(k=u.A)}k&&
(b[101]=k,b[128]=h);m&&(b[137]=m);await hc(this,v,E||1,P||0,q,l,c,b);!E||y||t||ic(this,c,d)}}else e?(this.aa(c,!0),delete this.l[c]):l!=p.K||p.U||t||(d?ic(this,c,d,!0):jc(this,c))};function kc(a,b){let c=a.h[b];if(c&&c.g){var e=c.h,d=c.i;S(a,7,2,c.U?128:c.A?256:c.j?512:0,[b,Math.round((c.l+e)*d),Math.round((c.H+e)*d),Math.round((c.width-e-c.B)*d),Math.round((c.height-e)*d)])}}
function ic(a,b,c,e){let d=a.l[b];if(d&&d.g){var f=d.port;let g,k=256;2==d.g&&(null==e&&(g=a.h[f.g])&&(e=f.tabId==g.K&&!g.U),e?(k|=128,d.g=1):k|=64);(e=d.i)&&!c&&(c=f.l);let h,m,l,q,p,t;if(c){h=c[0];m=c[1];l=c[2]||h+1;q=c[3]||m+1;p=c[4];if(c=!e&&f.l)h+=c[0],m+=c[1],l=Math.min(l+c[0],c[2]),q=Math.min(q+c[1],c[3]);if(f=a.g[f.tabId])t=f.I}S(a,9,1,k,[b,h,m,l,q,p,t])}}
n.ha=function(a){var b=this.o;let c=this.g;var e=this.h;let d=a?[e[a]]:A(e);a=[];e={};for(var f of d)!f||f.U||f.ga||b[f.K]||a.push(f.K);if(a.length)for(let g of A(this.l))g.g&&(b=g.port,f=b.tabId,a.includes(f)&&((f=b.h?b:c[f])&&f.update&&(f.update=!1,f.postMessage([14,!1])),g.h?b.h?b.postMessage([15,null,g.id]):dc(this,b,null,e):ic(this,g.id,null,!0)))};function lc(a,b){let c=a.h,e;if(b=null==b?A(c):(e=c[b])?[e]:null)for(e of b)Ab(a,e.K)}
function Ab(a,b,c,e){e=0!=e;let d=c?0:2;c=c?32:64;for(let f of A(a.l))f.g&&f.port.tabId==b&&f.g!=d&&(e||f.h)&&(f.g=d,S(a,8,1,c,[f.id]))}function jc(a,b){let c=a.l[b];c&&1==c.g&&(c.g=2,S(a,8,1,64,[b]))}function mc(a,b,c,e){var d=a.za;let f=(d&b)!=((c?255:128)&b);a.za=c?d|=b:d&=~b;f&&(c=a.j[-32],b=a.j[-33],c=a.ta=0!=c&&(d&c)==c,d=a.Ga=0!=b&&(d&b)==b,a.Va=(c||d)&&e||null)}
n.Na=function(a,b,c,e,d){let f=this.h[a];if(f)if(f.ga?e&&(J.clearTimeout(f.ga),f.ga=null):e||=-1,0<=e)f.o|=b,f.s|=c,e&&(f.ga=J.setTimeout(this.Na,e,a));else{b|=f.o;c|=f.s;f.o=f.s=f.ga=null;if(b){for(let g of A(this.m))g.h&&g.g==a&&(g.update=!0);d?this.P(d):browser.windows.get(a,this.P);browser.tabs.query({windowId:a,active:!0},this.P)}if(c){if((a=this.h[a])&&!a.U&&!a.ga&&(a=a.K,!this.o[a])){b=this.l;for(let g in b)c=b[g],c.g&&c.port.tabId==a&&1==c.g&&S(this,8,1,1152,[g])}}else this.ha(a)}};
n.P=function(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,e=this.h[c];if(e){var d=!a.windowId;if(d){b&&(e.i=this.Fa);var f=e.j="minimized"==a.state,g=e.A="maximized"==a.state;f||(e.width=a.width,e.height=a.height,e.m=a.left,e.u=a.top,f=e.U,a=e.U="fullscreen"==a.state,g=g&&-e.m,0<g&&16>=g&&g==-e.u&&(e.h=g),a==f||b||(a?lc(this,c):this.ha(c)))}else{if(e.I&&Ya(a.url))return;a.active&&(e.K=a.id);a.width&&(e.G=a.width);a.height&&(e.C=a.height)}if(!e.j){a=
e.width;let k=e.G;g=e.height;f=e.C;let h=!x&&(k>a||f>g);if(h||!k||!f){d||h&&browser.windows.get(c,this.P);return}d=a-k;a=d/2;0<=a&&16>=a?(e.h=a,e.l=e.B=0):(a=e.h,x||ba?e.l=d-2*a:e.B=d-2*a);d=g-f-2*a;d>=(e.J?20:50)&&d<=Fa&&(e.H=d);e.I=!0}b||kc(this,c);return e}}};function zb(a,b){return a.o[b]?!0:(a=a.g[b])&&a.refresh?(a.refresh=!1,browser.tabs.reload(b),!0):!1}
n.$b=function(a,b,c,e){a.D=b;a.B=c;a.refresh&&!e&&(a.refresh=!1);null==a.ea&&Zb(this,a);this.ha(a.g);0<this.H&&a.h&&1==a.X&&(this.j[11]?.test((new URL(b)).hostname)||cc(this))};n.bc=function(a,b,c,e,d){a.A=b;a.I=d;a=[a.j,a.tabId,a.g,e,d];e={};e[110]=b;e[128]=c;S(this,21,1,0,a,e)};
n.dc=function(a,b,c,e,d){let f=a.tabId,g=this.g[O(f,c)];if(g){var k=g.l;g.sa=e;if(g.l=d){var h=a.l;h&&(d[0]+=h[0],d[1]+=h[1],d[2]=Math.min(d[2]+h[0],h[2]),d[3]=Math.min(d[3]+h[1],h[3]));if(k&&k.join()!=d.join()){k=this.g;a=O(a.tabId,"");c=a+c;for(let m in k)m.startsWith(a)&&(h=k[m],h.i==c&&g.postMessage([16,b,h.ea,h.sa]))}}if(!this.o[f]){ic(this,e,d);for(let m of A(this.l))m.port==g&&m.g&&m.h&&!m.i&&g.postMessage([15,null,m.id])}}};
function dc(a,b,c,e){var d=a.g;c=[16,c];a=[b];for(let f;f=d[b.i];b=f){if(e)if(e[b.id])break;else e[b.id]=!0;a.push(f)}for(e=a.pop();b=a.pop();e=b)d=b.sa,c[2]=b.ea,c[3]=d,c[4]=d?null:b.D,c[5]=d?null:b.fa,e.postMessage(c)}function ec(a,b,c){a=a.g;b=O(b,"");let e=0;for(let d in a)d.startsWith(b)&&(a[d].postMessage(c),e++);return e}
n.va=function(a,b){let c={},e={files:["content.js"],target:c,injectImmediately:!0};b?c.frameIds=[b]:c.allFrames=!0;if(a instanceof Array)for(;b=a.shift();)b.discarded||(c.tabId=b.id,browser.scripting.executeScript(e).catch(()=>null));else if(b=a)c.tabId=b.id||b,browser.scripting.executeScript(e).catch(()=>null)};function nc(a,b,c,e){null==c&&(c=b.v==a.R);S(a,6,2,17|(c?2048:1024)|(b.A?256:b.j?512:0),[b.v,b.g,b.width,b.height,b.m,b.u,b.i],{[117]:e})}
async function ub(a){var b=browser.windows.getAll({windowTypes:["normal","popup","app"]}),c=browser.tabs.query({active:!0});[b,c]=await Promise.all([b,c]);let e={};if(c)for(let d of c)e[d.windowId]=d;for(let d of b)b=e[d.id],c=a.P(d,!0)||a.eb(d,!0,b),nc(a,c,d.focused,d.title||b&&b.title)}async function oc(a){await pc("system.display")&&(a.kb=(await browser.system.display.getInfo(null))[0].displayZoomFactor)}
n.Fb=function(a){let b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=this.jc++);var e=b.id,d="top"==a.name;a.tabId=e;a.g=0>b.index?null:b.windowId;a.m=!0;a.u=!1;a.update=d;a.h=d;a.ea=d?0:a.sender.frameId;a.J=0;a.D=a.sender.url||d&&b.url||null;a.fa=null;this.m[c]=a;d&&(this.g[e]=a);a.D&&(a.X=Ub(this,(new URL(a.D)).hostname));a.onMessage.addListener(this.Gb.bind(this,a));a.onDisconnect.addListener(this.wa);Zb(this,a)}};
n.wa=function(a){browser.runtime.lastError;if(a.m){a.m=!1;var b=O(a.tabId,a.ea),c=this.Z,e=this.l,d,f=this.ja,g=this.i,k;for(let h in c)c[h].port===a&&delete c[h];for(let h in e)if(d=e[h],d.port===a)this.aa(h),delete e[h];for(let h in f)f[h]===a&&delete f[h];for(let h in g)(k=g[h],k.port!==a||k.j)||delete g[h];this.Va===a&&mc(this,255,!1);delete this.m[a.id];delete this.g[b];a.h&&delete this.g[a.tabId];a=this.B;for(let h in a)b==a[h].h&&delete a[h]}};
n.Gb=function(a,b){let c=b.shift();b.unshift(a);switch(c){case 21:this.$b.apply(this,b);break;case 24:this.bc.apply(this,b);break;case 22:this.dc.apply(this,b);break;case 23:this.cc.apply(this,b);break;case 41:this.Eb.apply(this,b);break;case 25:this.ya.apply(this,b);break;case 26:yb(this,a.tabId,!0,!0,!1,a,b[1],b[2],b[3]);break;case 27:this.Wb.apply(this,b);break;case 28:this.aa(4294967295);break;case 29:this.Ya.apply(this,b);break;case 30:this.Ya.apply(this,b);break;case 31:this.zb.apply(this,b);
break;case 32:this.Cb.apply(this,b);break;case 39:this.Ab.apply(this,b);break;case 33:this.tb.apply(this,b);break;case 34:this.yb.apply(this,b);break;case 35:this.Bb.apply(this,b);break;case 36:this.Vb.apply(this,b);break;case 37:this.Hb.apply(this,b);break;case 45:this.sb.apply(this,b);break;case 46:this.vb.apply(this,b)}};
n.$a=function(a){let b=a.type;var c=a.v,e=a.j,d=a.g,f;if(1==b){let l=d[0];if(f=this.na[l])b=f.type,delete this.na[l]}switch(b){case 3:0<=this.ia&&(this.ia=-1,Lb());var g=d[0],k=d[5],h=d[6],m=d[4];d=d[8];this.Y=g;qc(this,h);rc(this,k,a);sc(this);if(m||d)d=(m?m/96:1)*(d?d/100:1),this.Fa=r&&1.245>d?1:d,ub(this),r&&this.kb&&oc(this);97>g&&this.La();Wb(this);break;case 4:g=this.j;this.da=!!(d[3]&2147483648);this.Ra=!!(d[3]&1073741824);rc(this,d[2],a);sc(this);e&2048&&(J.idm=this);g[-6]=0<(e&64);g[-10]=
0<(e&1024)||Wa;g[-5]=0<(e&32);g[-1]=0<(e&2);g[-8]=0<(e&256)||2>c;g[-9]=0<(e&512)||2>c;g[-32]=d[0];g[-33]=d[1];g[12]=a[12];g[17]=a[17];g[23]=a[23];109>this.Y?g[23]=Xa:110>this.Y&&(g[23]+=ta("|Erfcbafr|hey|trg"));Y(g,a,1);Y(g,a,2);Y(g,a,3);Y(g,a,4);Y(g,a,10);Y(g,a,9,2);Y(g,a,11,2);Y(g,a,20);Y(g,a,21,1);tc(g,a,19);tc(g,a,18,1,1);(this.I||this.Sa)&&wb(this);break;case 18:f=d[0];d=d[1];e=I[d?-d:f];if(!e)break;d=this.$[f]={};c=e[2];d.X=f;d.kc=e[0];d.lb=e[1];for(g in a)(g=parseInt(g))&&(102==g||110<g&&150>
g)&&(d[g]=c.includes(g)?RegExp(a[g]):a[g]);for(k of c)(h=d)[m=k]||(h[m]=La);g=this.$.map(pa(102)).filter(da);this.Ua=RegExp("^https?://(?:"+g.join("|")+")","i");Y(d,a,101,2);break;case 5:uc(this,d[0],e,d[1]);break;case 6:if(e&4)break;uc(this,f.g[0],e,d[2],d[1]);break;case 8:a=d[0];d=e&32;if(4294967295==a)ec(this,this.u,[13,!1]),this.u=null;else if(a=this.l[a])a.g=d?0:2;break;case 11:4294967295==d[0]&&(yb(this,this.u,!0,!0),this.u=null);break;case 12:try{let l=a.g[5];d=4==l?2:3;if(1==l||2==l){if(Xb(this,
a)){let q=a[4];if(this.j[3].test(q))1==l?d=6:l=4;else if(this.j[-1]||this.j[4].test(q))d=6;a[8]|=256}if(3==d){let q=this.h[this.R];q&&this.o[q.K]&&(d=1)}}if(4!=l)hc(this,a,d);else{switch(a.g[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}vc(this,a)}}catch(l){hc(this,a,0)}break;case 13:a=f.g[0];g=f.g[5];d=d[1];k=3==d;if(3>=g)f.j&128?fc(this,a,k):this.M(a,k);else if(5==g)if(d){if(f=(m=this.i[a])&&m.m)d=m.url,g=m.method,k=m.requestHeaders,(h=m.i)&&((h=wc(h,k,!0))??
(g="GET")),m.port.postMessage([19,a,f,d,g,k,h])}else xc(this,a);break;case 20:d=a[123];g=!d;a=[a.l];k={};x&&(h=this.S)&&(k[122]=h,d&&(g=h.substr(2).split(";",1).shift()==d));k[121]=this.v;S(this,1,2,g?2:4,a,k);break;case 24:yc(this,a);break;case 22:zc(d[0],d[1],a[131],a[130]);break;case 100:e&1&&S(this,100,1,0,[a.l],a);break;default:e&1&&S(this,1,2,0,[a.l])}};
async function zc(a,b,c,e){null==Ha&&(Ha=await pc("notifications")||!1);Ha&&(browser.notifications.create(a.toString(),{type:"basic",title:e??"",message:c,iconUrl:"images/logo48.png"}),b&&J.setTimeout(browser.notifications.clear,1E3*b,a.toString()))}async function yc(a,b){let c=await U(b[6],!!(b.j&16));b=[b.l,c?c.length:0];let e={[51]:V(c)};S(a,1,2,c?2:4,b,e)}
async function vc(a,b){try{let g,k=b.i||b.g[2],h=b.g[8],m=a.l[h];if(m&&m.port)g=m.port;else if(k in a.m)g=a.m[k];else if(k=await Yb(a,b))g=a.m[k];else{let l=await browser.windows.getLastFocused();if(l){let q=a.h[l.id];q&&(g=a.g[q.K])}}if(g){b.i=g.id;var c=a.h[g.g];if(c&&c.g){var e=a.g[g.tabId];e&&e.update&&(e.update=!1,e.postMessage([14,!0]));var d=Sb(a),f=[15,d.g,h];d.H=b;h||f.push(b[6],b[17],b[50],b[31],b[133],b[134]);g.h||dc(a,g,d.g);g.postMessage(f)}else hc(a,b,1)}else hc(a,b,0)}catch(g){hc(a,
b,0)}}async function hc(a,b,c,e,d,f,g,k){-1!=c&&(e|=0==c?4:2,k||={},k[8]=b[8],d=[b.l,c,d,g,f,-1],b.j&32&&(3==c||2==c)&&(b=await U(b[6],!!(b.j&16)))&&(d[5]=b.length,k[51]=V(b)),S(a,1,2,e,d,k))}n.Db=function(a){Qb(this,a).j=!0;x&&browser.windows.get(a.windowId,this.P)};
n.ab=function(a,b){var c=a.tabId,e=a.frameId;let d=a.url;var f=a.transitionType,g=a.frameType,k=a.documentId;let h="prerender"==a.documentLifecycle;this.O!=c||Ya(d)||(this.O=null);e&&h&&"outermost_frame"==g&&(e=a.frameId=0);f=f&&f.endsWith("_subframe");var m=!0;if(g=this.B[O(c,e)]){m=g.m;g.m=h?k:null;if(m&&m==k)return;k=g.o;m=!(d&&k&&(new URL(d)).hostname==(new URL(k)).hostname);g.o=d}else h&&(g=Qb(this,a),g.m=k);!f&&this.o[c]&&R(this,m,c);if(k=this.g[O(c,e)])if(this.u&&(a=this.h[k.g])&&a.K==this.u&&
this.aa(4294967295),b){a:{b=k.D;c=new URL(b);e=new URL(d);if(c.origin==e.origin&&c.pathname==e.pathname)switch(Ub(this,c.hostname)){case 1:if("/watch"==c.pathname&&c.searchParams.get("v")==e.searchParams.get("v")){b=!0;break a}break;case 4:if((c.pathname.startsWith("/p/")||c.pathname.startsWith("/reel/"))&&c.searchParams.get("img_index")==e.searchParams.get("img_index")){b=!0;break a}}b=d==b}if(!b){b=this.l;var l;for(let q in b)if(l=b[q],l.port===k)2==k.X||4==k.X?jc(this,q):(this.aa(q),delete b[q]);
k.J++;k.D=d;k.h&&(k.update=!0);k.postMessage([17,!0])}}else this.wa(k,!0),f&&"about:blank"==k.D&&this.va(c,e);else f&&"about:blank"==d?(Qb(this,a),this.va(c,e)):g&&g.j&&(g.D||!b)?g.j=!1:x&&browser.tabs.get(c,this.P)};n.ub=function(a){return this.ab(a,!0)};
n.eb=function(a,b,c){let e=a.id;c={v:e,width:a.width,height:a.height,m:a.left,u:a.top,i:this.Fa,h:8,H:Ea,l:0,B:0,J:"popup"==a.type||"app"==a.type,U:"fullscreen"==a.state,A:"maximized"==a.state,j:"minimized"==a.state,K:c&&c.id,C:c&&c.height,G:c&&c.width,I:!x,g:null,ga:null};Object.setPrototypeOf(c,qb.prototype);this.h[e]=c;a.focused&&(this.R=e);b?(browser.tabs.query({windowId:e,active:!0},this.P),browser.tabs.query({windowId:e,url:N},this.ac),browser.tabs.query({windowId:e,url:N},this.va)):x&&this.Ha==
e&&(this.Ha=null,browser.tabs.query({windowId:e,active:!0},this.P));return c};n.ac=function(a){for(let b of a)Qb(this,0,b.id,!0,b.url)};n.fb=function(a){S(this,5,1,32,[a]);delete this.h[a];this.s==a&&vb(this)};n.Ub=function(a){if(0<a){this.s&&browser.windows.update(this.s,{drawAttention:!0});let b=this.h[a];b&&(this.R=a,b.g||nc(this,b,!0),browser.windows.onBoundsChanged||browser.windows.get(a,this.P),zb(this,b.K))}else this.R=null};n.Tb=function(a){this.Na(a.id,!0,!1,-1,a)};
function uc(a,b,c,e,d){let f=a.h[b];f?(e&&(f.i=e),d&&(f.g=d),e=!!(c&128),f.U!=e&&(f.U=e)&&lc(a,b),(d||c&4096)&&kc(a,b)):a.fb(b)}n.Mb=function(a,b,c){let e=c.active;c=c.windowId;let d=e&&this.h[c];d&&(d.g||nc(this,d));"complete"==b.status&&(a=this.g[a])&&!a.u&&(a.u=!0,e&&this.ha(c))};n.Lb=function(a){let b=this.g,c=this.B,e=O(a,"");this.O==a&&(this.O=null);let d=b[a];d&&this.wa(d,!0);for(let f in b)f.startsWith(e)&&this.wa(b[f],!0);for(let f in c)f.startsWith(e)&&delete c[f];delete this.o[a]};
n.Jb=function(a){let b=a.tabId;a=a.windowId;this.za=0;this.u&&this.aa(4294967295);var c=this.h[a];c?(Ab(this,c.K),c.K=b,(c=this.O)&&b!=c&&(this.s?browser.windows.update(this.s,{drawAttention:!0}):this.C&&this.I&&(this.O=null,J.setTimeout(browser.tabs.remove,250,c))),browser.tabs.get(b,this.P),zb(this,b)||this.ha(a)):x&&(this.Ha=a)};n.Kb=function(a,b){b=b.newWindowId;for(let c of A(this.m))c.tabId==a&&(c.g=b);Ab(this,a,!0)};n.xb=function(a){this.s&&"idle"==a&&browser.windows.update(this.s,{focused:!0})};
n.Ya=function(a,b,c){if(a.h){let e=a.tabId;a=a.g;let d=this.h[a];this.u&&this.aa(4294967295);if(d&&d.K==e){let f=!1;b&&(d.G=b,f=!0);c&&(d.C=c,f=!0);Ab(this,e,!1,f);this.Na(a,f,!1,500)}}else a.sa&&(b=this.g[a.i])&&b.postMessage([16,null,a.ea,a.sa])};n.zb=function(a,b,c){(b=ua[b])&&mc(this,b,c,a)};n.Cb=function(a,b,c){0==b&&mc(this,128,c,a)};n.Ab=function(a,b,c,e){this.Ca=a.id;a.G=b;a.C=c;a.H=e};n.tb=function(){mc(this,255,!1)};
n.yb=function(a,b,c,e){var d=a.j;d&&(a=32,d=[d,null==c?(a|=16,-2):c],S(this,16,1,a,d,{[110]:b,[115]:e}))};n.Vb=function(a,b,c){if(a=this.i[b])S(this,16,1,48,[a.id,0],{[115]:c}),a.da=!1,a.Ka&&this.M(a)};n.vb=function(a,b,c,e){null!=b&&(a.N=b?1:-1);null!=c&&(a.s=c?1:e?2:-1)};n.Hb=function(a,b,c,e){S(this,19,2,0,[b,c,a.tabId,a.j],e)};
n.sb=function(a,b,c){if(a=this.i[b]){if(0>a.m&&null!=c){a=new Uint8Array(c.length);for(let e=0;e<c.length;++e)a[e]=c.charCodeAt(e);c=a}S(this,16,1,48,[b,-1],{[115]:c});xc(this,b)}};function xc(a,b){if(b=a.i[b])b.m=null,b.s=null,b.Ka&&a.M(b)}
function Ac(a,b){let c=a.j;if(b.A||a.o[b.tabId]||!c[-6])return 1;if(b.l)return 6;if(b.h&&c[-1])return 1;a=b.xa;let e=b.V=W(a.pathname);return c[9].test(a.hostname)||c[19].test(a.href)?1:2==(b.W&7)&&(b.N||c[-10])?a.pathname.endsWith("/")||c[21].test(a.pathname)?1:c[1].test(e)||!c[20].test(e)?4:1:6}
function Bc(a,b){let c=!b.g;if(b.l&&c)return 3;let e=a.j;var d=e[18];let f=e[1];var g=b.xa;let k=b.V,h=b.oa||(g.search?null:k),m=b.h,l=Na.includes(b.type),q=!b.N;var p=!l&&d.exec(g.href);if(p){var t=d.ec,v=d.fc;let w=d.hc,y=d.ic;for(d=1;d<p.length;++d)if(p[d]){t=t[--d];if(null===t)break;var u=void 0;p=0;t.includes("G")&&(u=!0,p|="GET"==b.method);t.includes("P")&&(u=!0,p|="POST"==b.method);if(u&&!p)break;u=t.includes("V")|t.includes("A")|t.includes("C");t.includes("H")&&(b.Z=!0);if((u?b.Z:m?!t.includes("S"):
t.includes("X"))||q&&t.includes("D"))return 1;let E,P,H;if(p=y[d]){p=p.exec(g.href);if(!p)break;g=v[d];if(v=g.F)H=!0,P=p[v];if(v=g.T)H=!0,E=p[v]}E||=W(P)||t.includes("T")&&(H=!0,k)||w[d];if(u)return E&&(b.V=E),m||(b.h=!0),b.g=!0,6;if(c&&(E?f.test(E):!H))return b.S=16777216,4;break}}if(!c)return 6;if(h&&(l&&e[2].test(h)||m&&e[4].test(h)))return 1;if(x&&(b.N||e[-10])){if(m&&e[3].test(h))return 6;if((!m||a.da)&&h&&f.test(h))return b.S=8,4}return 6}
function Cc(a,b){if(b.ma)return X(a,6,b),6;var c=b.statusCode;if(200!=c&&206!=c&&304!=c)return 1;var e=Z(b.o,"Content-Type"),d=Z(b.o,"Content-Disposition"),f=Dc(e).toLowerCase();let g="attachment"==Dc(d).toLowerCase();c=b.h;var k=b.B;if(b.la=k&&!g&&"text/html"==f){if(b.j){var h=Rb(a,b);h&&(h.l=!0);X(a,5,b)}return 1}if(c?b.A:b.g)return 1;if(a.da&&k&&g)return 4;let m,l,q,p,t,v;var u;let w;let y,E=a.j,P=b.port,H=b.xa;var ka=H.hostname;let xa=H.pathname,z=(d=Ec(d,"filename")||Ec(e,"name"))&&W(d);if(d){if(!z&&
!c)return 1;if(z&&(!c||5>=z.length)){var B=Ec(e,"charset");y=!B||"utf-8"==B||"utf8"==B;B=!0}}B||(d=xa.split("/").pop(),(z=b.V||W(d))&&z.toLowerCase()==f.split("/").pop()&&(B=!0));if(!B){e=E[10].test(f);var K=za[f];K&&(K=K.split("|"),z&&K.includes(z)?B=!0:c&&ab(z)?B=!0:(c?e:z)||(B=!0,w=e,z=K[0]));!B&&z&&(g&&k?B=!0:e?B=w=!0:K||$a(z)||(B=w=!0))}if(c){K=Ub(a,ka);k=a.$[K];e=xa+H.search;switch(K){case 0:break;case 1:if(k[111].test(e))m=B=!0,z=null;else if(k[112].test(e))l=!0;else if(k[115].test(e)&&"application/json"==
f)v=!0;else if(k[113].test(e)||k[114].test(e))q=!0;break;case 2:(ka=k[111].exec(e))&&(Za(f)||"text/html"==f)?(f=ka[1]&&k[112].exec(P.D))&&ka[1]!=f[1]||(q=!0):k[114].test(e)?t=!0:g&&"image"==b.type&&"MP4"==z&&(u=!0);break;case 3:"M4S"==z&&(B=!0);ka==k[111]&&k[112].test(xa)&&Za(f)&&(q=!0);break;case 4:k[111].test(e)&&Za(f)&&(t=!0);break;case 5:k[111].test(e)&&"text/html"==f&&(t=!0);break;case 6:k[111].test(e)&&(q=!0);break;default:k[111].test(xa)&&(t=!0)}B&&("M3U8"==z||"F4M"==z||"MPD"==z?q=!0:"F4F"==
z&&(d.endsWith("Seg1-Frag1")||d.endsWith("Seg1-Frag2")||d.includes("Seg1-Frag2_"))&&(p=!0));"ASF"==z&&((f=Z(b.o,"Content-Length"))&&102400>=parseInt(f)&&(u=!0),"DCLK-AdSvr"==Z(b.o,"Server")&&(u=!0))}if(u)return 1;B&&(c&&E[3].test(z)?m=!0:c&&E[4].test(z)?b.g=!0:!b.g&&E[1].test(z)&&(h=!0));if(m){let Ob,Pb;if(b.Z)m=!1;else if(u=E[11])u.test(H.hostname)?m=!1:(Ob=a.g[b.tabId])&&(Pb=Ob.D)&&u.test((new URL(Pb)).hostname)&&(m=!1)}if(t||v)t&&0>P.N||v&&0>P.s?q=!0:l=b.da=!0;if(q||p)!b.port||"POST"==b.method&&
!b.i?l=!1:(b.m=p?-1:1,l=!0);if(!h&&!m&&!l)return 1;B&&(b.oa=z);y&&(b.Y=d);b.j|=l;b.S=m||l?256:16|(c?4096:0)|(w?8388608:0);return h?4:m?2:5}
function X(a,b,c,e,d){var f=c.url,g=c.W||T(f);let k=c.requestHeaders,h=1==(g&7);if(!e&&!k&&h)if(void 0===d){if(d=Z(k,"Cookie"),null==d)return U(f).then(y=>X(a,b,c,e,y||null))}else d=V(d);let m=e?e.id:c.id,l=c.port&&c.port.id,q=c.timeStamp,p=c.S,t=c.o,v=c.$,u=c.v,w=0;3==(u?u.length-u.replaceAll(".","").length:0)?p|=33554432:2<(u?u.length-u.replaceAll(":","").length:0)&&(p|=4194304);g&16&&(p|=2097152);"POST"==c.method&&(p|=512);e&&(w|=129);4>b&&x&&(w|=1);c.j&&c.m&&(w|=1);c.j&&5!=b&&(w|=32);c.h&&(w|=
16);c.J&&(w|=8192);c.B&&(w|=c.C?2048:4096);g=[m,l,D(q),c.statusCode,g&7,b,c.tabId,c.frameId];f={[6]:$b(f,h&&a.N),[12]:c.statusLine,[17]:c.fa,[4]:c.oa,[100]:c.Y,[127]:c.ra,[129]:c.na,[2]:c.v,[122]:a.v,[8]:p,[11]:Fc(k),[13]:Fc(t),[18]:Fc(v)};c.i&&(f[14]=wc(c.i,k));c.R&&(f[19]=wc(c.R,v));k||(f[50]=Gc(a,c),f[51]=d,f[54]=navigator.userAgent);x&&(f[122]=Mb(a,c.proxyInfo,Z(k,"Proxy-Authorization")),f[55]=Mb(a,c.ba,Z(v,"Proxy-Authorization")));if(!c.la||!c.C)if(d=a.g[c.tabId])f[7]=d.D;return!!S(a,13,1,w,
g,f)}function Hc(a,b,c,e){if(x){if(X(a,b,c)){if(r&&!e){c.I=!0;return}return x?new Promise((d,f,g=a)=>{c.H=d;c.G=f;Nb(g,c)}):a.M(c,!0)}c.g=!0}else c.ka=!0}
n.M=function(a,b,c){let e=this.i,d;if(G(a)||(a=e[a])){var f=a.id,g=0<a.statusCode;if(b){if(a.B||a.J)c=g||!a.requestHeaders,(g=Rb(this,a))&&g.j&&a.C?browser.tabs.remove(a.tabId):r&&c&&!a.J&&(d={redirectUrl:"javascript:void(0)"});d||={cancel:!0};a.I=!0}else c&&(d={[g?"responseHeaders":"requestHeaders"]:c});(c=a.H)&&void 0!==b&&(a.H=a.G=null,c(d||{}));if(b=a.G)a.H=a.G=null,b();if(a.Da||a.m||a.da)return a.Ka=!0,d;delete e[f];a.s&&delete e[a.s];a.u&&delete e[a.u];return d}};
n.cb=function(a){var b=a.type,c=a.tabId,e=a.frameId;if(!(0>c&&(x?a.originUrl==Va:a.initiator==Ua))){var d=a.url,f=a.method,g=T(d);if(g&&("GET"==f||"POST"==f)&&d!=this.Qa){e&&"outermost_frame"==a.frameType&&(e=a.frameId=0);var k=a.id=a.requestId,h=this.i[k],m=this.Ga,l="POST"==f,q="image"==b,p=r&&"other"==b,t=!p&&0>c&&(x||0>e),v=0<c&&b.endsWith("_frame"),u=t?null:this.g[O(c,e)];if(u||v||t||p||h){x&&l&&h&&hb(h.statusCode)&&(f=a.method="GET",l=!1);v&&Qb(this,a,null,!1);if(!m&&l&&a.requestBody){l=a.requestBody;
var w=l.raw;if(w)for(let y=0;y<w.length&&(w[y].bytes||(w=null));y++);if(!(w||l.formData||r&&l.error))return}if((l=this.Ca)&&(w=u?u.id==l&&u:this.m[l])&&d==w.C){p=w.G;if(l=w.H)a.Y=l,a.oa=W(l);u||=w;this.Ca=null}l=new URL(d);l.hash="";a.xa=l;a.W=g;a.l=this.ta;a.A=m;a.C=v&&"main_frame"==b;a.B=v;a.J=p;a.ja=t;a.h=t||Oa.includes(b);a.g=q;a.j=this.Ua.test(d);a.i=a.requestBody;a.port=u;a.N=g&8||(x?a.proxyInfo&&"https"==a.proxyInfo.type:this.ua[g]);0>c&&(a.tabId=null);0>e&&(a.frameId=null);if(h)a.id=h.id,
a.port=u=h.port,a.l=h.l,a.A=h.A,a.fa=h.fa||h.url,a.$=h.$||h.requestHeaders,a.R=h.R||h.i,x&&(a.ba=h.ba||h.proxyInfo);else if(x&&t)for(let y of A(this.i))if(y.ia&&!y.u&&d==y.url&&b==y.type&&f==y.method){a=y;a.u=k;break}if(a.h&&!q){b=this.ja;c=b.Xb;e=c.indexOf(d);if(0<=e)c.splice(e,1);else for(;30<=c.length;)delete b[c.shift()];b[d]=u;c.push(d)}switch(a.action=Ac(this,a)){case 1:a.g=!0;case 6:Nb(this,a);break;case 4:return Hc(this,1,a)}}}}};
n.Ob=function(a){var b=this.i[a.requestId];if(b){var c=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.I){if(b.ja&&!b.port&&(a=Z(c,"Referer")))for(var e of A(this.m))if(e.D==a){b.port=e;break}if(b.port&&"xmlhttprequest"==b.type){var d,f;e=0;for(d of c)if("accept"==d.name.toLowerCase()&&(f=db(d.value)))break;else e++;if(f){a=f[3];let k=f[4];var g=x;f[1]||f[5]?d.value=f[1]+(f[5]&&f[2]||"")+f[5]:c.splice(e--,1);if("int"==a)return this.M(b,!1,g&&c);if("pxr"==a||"pfm"==a)b.s=k,this.i[k]=
b}}x&&b.proxyInfo&&Mb(this,b.proxyInfo,Z(c,"Proxy-Authorization"),!0);if("POST"==b.method&&(!b.i||b.i.error&&0<Z(c,"Content-Length")))return this.M(b);switch(b.action=Bc(this,b)){case 1:b.g=!0;break;case 4:return Hc(this,1,b);case 3:return Hc(this,3,b)}if(g)return{requestHeaders:c}}}else if(x&&0>a.tabId&&"xmlhttprequest"==a.type&&(x?a.originUrl==Va:a.initiator==Ua)){b=a.requestHeaders;c={};for(d=0;d<b.length;d++)f=b[d],e=f.name.toLowerCase(),e.startsWith("x-idm-")?c[e.substr(6)]=g=!0:"origin"==e&&
f.value==Ua&&(c[e]=g=!0);if(g){for(g=0;g<b.length;g++)d=b[g],f=d.name.toLowerCase(),c[f]?b.splice(g--,1):f.startsWith("x-idm-")&&(d.name=d.name.substr(6));return{requestHeaders:b}}}};n.Nb=function(a){if(!a.statusCode&&a.redirectUrl==a.url){a=a.requestId;let b=this.i[a],c=b&&Rb(this,b);c&&!b.statusCode&&c.i==a&&(b.ia=!0)}};
n.Rb=function(a){let b=this.i[a.requestId];if(b){var c=b.port,e=b.type,d=b.statusLine=a.statusLine,f=b.statusCode=a.statusCode||parseInt(d.split(" ",2).pop()),g=a.responseHeaders;if(b.I||204==f&&d.includes(" IDM "))return this.M(b,!0);b.v=a.ip;b.ca=a.timeStamp;b.na=D(a.timeStamp-b.timeStamp);b.o=g;b.ma=gb(f);if("image"==e&&(d=Z(g,"Content-Type"))&&d.toLowerCase().startsWith("image"))return this.M(b);"quic"==Z(g,"Client-Protocol")?b.W|=16:(d=Z(g,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=
Z(g,"Transfer-Encoding")&&(b.W|=16);if(c&&"xmlhttprequest"==e&&!b.s&&2==c.s){e=qa.map(Z.bind(J,g));e.unshift(b.url);e=e.join("|");g=5381;d=e.length;for(f=0;f<d;f++)g=33*g+e.charCodeAt(f)>>>0;c=b.s=`${c.id}-${g}`;this.i[c]=b}switch(b.action=Cc(this,b)){case 1:return x&&this.M(b);case 4:return Hc(this,2,b,a);case 3:return Hc(this,3,b,a)}}};
n.Sb=function(a){let b=this.i[a.requestId];if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){let c=Rb(this,a);c&&(c.D=a.url,c.fa=c.s)}b&&(b.v||(b.v=a.ip),2==b.action?X(this,4,b):5==b.action&&X(this,5,b),x&&this.M(b))};n.Pb=function(a){(a=this.i[a.requestId])&&(x||!a.ka||a.Da?this.M(a):J.setTimeout(this.M,250,a))};n.Qb=function(a){this.M(a.requestId)};
async function tb(a){var b={url:L.homepage_url};Ca&&(b.firstPartyDomain=null);var c=browser.storage.local.get(null);b=browser.cookies.getAll(b);let e=browser.extension.isAllowedIncognitoAccess();[c,b,e]=await Promise.all([c,b,e]);a.ib=c.version;a.ma=c.silent;a.V=c.lastupt;a.Ta=e;x&&(a.I=!!c.consent);c=c.client;let d;if(b)for(let f of b)switch(f.name){case "idmwebext_cid":d=parseInt(f.value);break;case "idmmzcc3_uri":a.Sa=f.value==Ua}qc(a,null,c,d);a.Ba()}
function qc(a,b,c,e){(b||=c||e)&&b!=a.ba&&(a.ba=b,c||browser.storage.local.set({client:b}),e||browser.cookies.set({url:L.homepage_url,name:"idmwebext_cid",value:String(b),expirationDate:2147483647}))}
function Wb(a){function b(m){m&&(this.O=m.id)}a.O&&(browser.tabs.remove(a.O),a.O=null);if(a.jb||!a.I){var c=!a.C,e=!a.Ta,d=!a.I,f=a.N,g=a.ra,k=a.ib,h=a.Ia;if(c){if(a.la&&a.ma)return}else a.jb=!1,h!=k&&(h&&browser.storage.local.set({version:h}),x&&browser.cookies.set({url:L.homepage_url,name:"idmmzcc3_uri",value:Ua,expirationDate:2147483647})),a.ma&&(a.ma=!1,browser.storage.local.set({silent:!1}));if(null!=k&&(d=!1,a.I=!0,h!=k?g&&k&&!f&&!d:!d))return;h=Ta+"current="+escape(h);k&&(h+="&previous="+escape(k));
g&&(h+="&manager="+(g?[g>>24&255,g>>16&255,g>>8&255,g&255].join("."):""));c&&(h+="&error=1");e&&(h+="&incognito=1");f&&(h+="&update=1");d&&(h+="&consent=1");x&&(h+="&mzffox=1");ba&&(h+="&opera=1");aa&&(h+="&msedge=1");d&&!c?(browser.idle&&a.L(5,browser.idle.onStateChanged,a.xb)&&browser.idle.setDetectionInterval(15),browser.windows.create({type:"popup",width:Math.min(Math.round(.85*screen.availWidth),1100),height:Math.min(Math.round(.85*screen.availHeight),900),url:h}).then(m=>{m&&m.id?(a.s=m.id,
a.O=m.tabs[0].id,R(a,!1,null,!0)):vb(a)})):browser.tabs.create({url:h},b.bind(a))}}function rc(a,b,c){null==b&&(b=fb(c[13]))&&(b=b[1]<<24|b[2]<<16|b[3]<<8);a.ra=b>>>0}function sc(a){a.N=103418624>a.ra;103424E3>a.ra?a.H=a.V?a.V+6E4*D(240*F()+480):Date.now():(a.H=a.V=null,browser.storage.local.remove("lastupt"))}
function cc(a,b){var c=Date.now();if(c>a.H||b&&!a.N)browser.storage.local.set({lastupt:a.V=c}),0<a.H&&(a.H=c+6E4*D(240*F()+480)),c="idmdwnlmfv4://idmreg://"+F().toString(36).substr(2),b?a.qa(c):J.setTimeout(a.qa,D(5E3*F()+5E3),c)}function Gc(a,b){a=a.B;b=O(b.tabId,b.frameId);var c;do b=(c=a[b])&&c.h,c=c&&c.D,"about:blank"==c&&(c=null);while(!c&&b);return c}
function bc(a,b){b=browser.i18n.getMessage(b);browser.scripting.executeScript({target:{tabId:a},func:function(c){window.alert(c)},args:[b]},Vb)}n.L=function(a,b,c){if(null==b)return!1;let e=ha(arguments);x&&(e[2]=function(){return c.apply(null,arguments)});this.Oa.push(e);b.addListener.apply(b,e.slice(2));return!0};
n.Aa=function(){let a=arguments.length?ha(arguments):null,b=this.Oa;for(let c=0;c<b.length;c++){if(a&&!a.includes(b[c][0]))continue;let e=b.splice(c--,1).pop(),d=e.splice(0,2).pop();d.removeListener.apply(d,e)}};function Gb(a){return browser.i18n.getMessage(a)||a}function $b(a,b){let c=a.lastIndexOf("#");c>a.indexOf("?")&&"!"!=a[c+1]&&(a=a.substr(0,c));!b||a.startsWith("idmdwnlmfv")||bb(a)||(a=`${"idmdwnlmfv"}4://${a}`);return a}
function T(a,b){a=a.split(":",1).shift().toLowerCase();a=va[a]||0;return b?a&7:a}function W(a){return(a=eb(a))?a[1].toUpperCase():""}function U(a,b){a={url:a};b&&(a.session=!1);Ca&&(a.firstPartyDomain=null);return browser.cookies.getAll(a).catch(()=>null)}function V(a){if(!G(a))return a;let b=[];for(let c of a)b.length&&b.push("; "),b.push(c.name,"=",c.value);return b.join("")}
function Fc(a){if(!a||!a.length)return null;let b=[];for(let c of a)b.push(c.name,": "),null!=c.value?b.push(c.value):c.binaryValue&&b.push(new Uint8Array(c.binaryValue)),b.push("\r\n");return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(let c of a)if(c.name.toLowerCase()==b){if(null!=c.value)return c.value;if(c.binaryValue)return la(c.binaryValue)}return null}
function Ec(a,b){if(!a)return null;let c,e;a=a.split(";");for(b=b.toLowerCase();a.length;){var d=a.shift();let g=d.indexOf("=");if(0<g){var f=d.slice(0,g).trim().toLowerCase();let k=f.endsWith("*");if(k)f=f.slice(0,-1).trimRight();else if(e)continue;if(f==b){f=d.substr(g+1).trim();d=f.length-1;if('"'==f[0]?'"'==f[d]:"'"==f[0]&&"'"==f[d])f=f.slice(1,d);if(k&&f.includes("'")){if(f=f.split("'",3),k=f.shift().toLowerCase(),f=f.pop(),((d="utf-8"==k||"utf8"==k)||!e)&&(c=Ic(f))&&(e=k,d))break}else c=Ic(f)}}else 0>
g&&null==c&&d.trim().toLowerCase()==b&&(c="")}return c}function Dc(a){const b=/[;,]/;return(a&&=a.split(b,1).shift().trim())&&!a.includes("=")&&Ic(a)||""}function Ic(a){try{return a&&decodeURIComponent(a)}catch(b){return unescape(a)}}
function wc(a,b,c){let e;var d;let f=[];if(e=a.raw)for(d of e){var g=d.bytes;if(g)f.push(c?la(new Uint8Array(g)):g);else return null}else if(d=a.formData)if(b=fa(b)?Z(b,"Content-Type"):b,(a=Dc(b).toLowerCase())&&"application/x-www-form-urlencoded"!=a)if("multipart/form-data"==a){var k=Ec(b,"boundary");k||="----WebKitFormBoundary"+F().toString(36).substr(2);for(g in d)for(let h of d[g])c&&h instanceof ArrayBuffer&&(h=la(new Uint8Array(h))),f.push("--",k,'\r\nContent-Disposition: form-data; name="',
g,'"\r\n\r\n',h??"","\r\n");f.push("--",k,"--\r\n")}else return null;else for(k in d){g=encodeURIComponent(k).replaceAll("%20","+");for(let h of d[k])h=h instanceof ArrayBuffer?escape(la(new Uint8Array(h))):null==h?"":encodeURIComponent(h),f.length&&f.push("&"),f.push(g,"=",h&&h.replaceAll("%20","+"))}else return null;c&&(f=f.join(""));return f.length?f:null}function mb(a){let b=a.length,c=b,e=0;for(;e<c;){let d=a.charCodeAt(e++);128<=d&&(2048<=d?(b+=2,d-55296&64512||e++):b++)}return b}
function Jc(){let a="llbjbkhnmlidjebalopleeepgdfgcpec"==Ga&&"ngpampappnmepgilojfohadhhmbhlaek";browser.management.get(a||"llbjbkhnmlidjebalopleeepgdfgcpec",function(b){browser.runtime.lastError;b&&b.enabled&&browser.management.setEnabled(a||Ga,!1)})}
function Jb(a,b){a=a.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\.");a=1==b?a.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):3==b?a.replace(/(?<![*?])\*(?!\*)/g,"[^/]*").replace(/\?\*/g,"\\?.*").replace(/\*\*/g,".*?"):a.replace(/\?/g,".").replace(/\*/g,".*?");2==b&&(a=a.replace(/(^|\|)([^|]+?)~/g,"$1(?:$2\\.)?").replace(/(^|\|)~/g,"$1(?:.*?\\.)?"));return"^(?:"+a+")$"}
function Y(a,b,c,e){if(b=b[c]||void 0){b=Jb(b,e);try{b=RegExp(b,1==e?"":"i")}catch(d){b=null}}a[c]=b||La}
function tc(a,b,c,e,d){b=b[c];let f=[],g=[],k=[],h=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)|\*+(?=\*)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(e){for(var m=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");m.length;){var l=m.shift();f.push(cb(l)?l:null);g.push(m.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(d){let q=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");m=/<([A-Z]):(.*?)>/g;l={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"};for(let p,t=0;q.length;++t)if(p=q.shift()){let v={},u=["^"],w="";for(let y,E=1;y=m.exec(p);++E)v[y[1]]=E++,w=RegExp.rightContext,u.push(RegExp.leftContext,"(",y[2].replace(/\*/g,l[y[1]]||".%%?"),")");u.push(w,"$");k[t]=v;h[t]=RegExp(u.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(m,"(?:$2)")}b=b.replace(/\*/g,".*?").replace(/%%/g,"*");b=e||d?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(q){b=
null}a[c]=b||=RegExp("(?!)");e&&(b.ec=f,b.hc=g);d&&(b.fc=k,b.ic=h)}function pc(a){return browser.runtime.lastError?null:browser.permissions.request({permissions:[a]})}function Vb(a){browser.runtime.lastError;a;!0}
const xb=[null,[!0,-8,"menu_download_link","link,image,video",Q.prototype.Ea],[!0,-8,"menu_download_link","page,frame,editable",Q.prototype.Ea,Ra],[!0,-8,"menu_download_selected","selection",Q.prototype.Pa],[!0,-9,"menu_download_all","page,frame,editable",Q.prototype.Pa],[r,-8,"menu_download_item","link",Q.prototype.Ea,["chrome://downloads/*"]]],Cb=Gb("tooltip_title"),Eb=Gb("tooltip_disabled"),Fb=Gb("tooltip_error"),Db="\n"+Gb("tooltip_text");
(async function(){var a=browser.runtime.getPlatformInfo();let b,c;navigator.userAgentData?b=navigator.userAgentData.getHighEntropyValues(["fullVersionList","uaFullVersion"]):b=browser.runtime.getBrowserInfo?.();c=browser.privacy?.websites?.firstPartyIsolate?.get({});var e=r&&browser.management.get("clhiejnehegdfknplplojohghjaklbae").catch(()=>null);[a,b,c,e]=await Promise.all([a,b,c,e]);if(a&&"win"!=a.os)return Bb(!1);aa&&Jc();a=navigator.userAgent;var d=a.match(/\s(?!(?:Chrome|Firefox|Gecko|Safari)\/)([A-Z]\w+)(?:\/(\d+(?:\.\d+){0,3}))?\b(?!.*\)\s+\S)/),
f=a.match(/\s(Chrome|Firefox)\/(\d+(?:\.\d+){0,3})\b/);a=f?f[1]:"UNKNOWN";let g=d?d[1]:a;f=f&&f[2]||"0.0";d=d&&d[2]||f;x&&(a="Mozilla");r&&navigator.brave&&(g="Brave");r&&e&&(g="Epic",Da=!0);if(G(b)){if(e=b.uaFullVersion)d=e;if(e=b.fullVersionList)for(let k of e){if(e=k.version)switch(k.brand){case "Chromium":a="Chrome";parseInt(e)==parseInt(f)?f=e:(g="UNKNOWN",d=e);break;case g:d=e}}else if(e=b.version)if(53<=parseInt(e)&&(f=e),e=b.name)g=e}e=f.split(/\D+/);Aa=`${a}/${f}`;Ba=`${g}/${d}`;browser.webRequest.ResourceType.OBJECT_SUBREQUEST&&
(M.push("object_subrequest"),Oa.push("object_subrequest"));G(c)&&(Ca=c.value);new Q})();
