var h;
if(!window.__idm_init__&&navigator.platform.startsWith("Win")&&"html"==document.documentElement.localName){window.__idm_init__=!0;"undefined"==typeof browser&&(browser=chrome);navigator.userAgent.includes("Edg/");navigator.userAgent.includes("Firefox/");navigator.userAgent.includes("OPR/");navigator.userAgent.includes("YaBrowser/");const Z=Object.values,aa=RegExp.prototype.test,O=Array.from,P=Array.prototype.includes,K=Math.random,Q=Function.call.bind(Array.prototype.slice),R=Function.apply.bind(Array.prototype.push),G=
Function.call.bind(Array.prototype.forEach),ba=Function.apply.bind(String.fromCharCode,null),H="dotAll"in RegExp.prototype?"s":"",ca=Function.call.bind(String.prototype.charCodeAt),da=String.fromCharCode;new TextEncoder("utf-8");const ea=["date","content-type","content-length"];function fa(a,b){return fetch(a,b).catch(()=>null)}function ha(a,b){b&&(a[b]=!0);return a}function y(a){return a.replace(/[a-z]/gi,function(b){return da((b=ca(b))+(13<(b&31)?-13:13))})}const ia={16:!0,17:!0,18:!0,45:!0,46:!0},
L=P.bind(["video","audio","object","embed"]),A=RegExp("(?!)"),ja=RegExp(" *\\$([<>{}|&*+=@!#%:?^~-])(\\d*) *"),ka=aa.bind(/^rgba?\(\d+,\s*\d+,\s*\d+,\s*0\)/),I=window.self===window.top;var D=window.origin||document.origin||location.origin,J=location,M=location.hostname.toLowerCase()+location.pathname+location.search,S=location.hostname.toLowerCase().split(".").at(-2),T=`idmrs://${S}/`,la=S?RegExp(`^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*${S}$`,"i"):A;function U(){browser.runtime.getFrameId?this.ja=
browser.runtime.getFrameId(window):I&&(this.ja=0);this.Ga=[];this.la=[];this.W=[];this.v={};this.hb();window.__idm_connect__=this.hb.bind(this,!0);this.j(1,window,"resize",this.wc);this.j(1,window,"scroll",this.xc);this.j(1,window,"blur",this.oc);this.j(1,window,"keydown",this.qb,!0);this.j(1,window,"keyup",this.qb,!0);this.j(1,window,"mousedown",this.qc,!0);this.j(1,window,"mouseup",this.sc,!0);this.j(1,window,"mousemove",this.rc,!0);this.j(1,window,"click",this.pc,!0);this.j(1,document,"beforeload",
this.mc,!0);this.j(1,document,"DOMContentLoaded",this.pb);"interactive"!=document.readyState&&"complete"!=document.readyState||this.pb()}h=U.prototype;h.u=0;h.B=0;h.na=-1;h.oa=-1;h.vb=1;h.s="";h.Z=0;h.m="";h.Ma="";h.L="";h.pa="";h.Ta=A;h.$a=RegExp(y('\\olgpst\\.frg\\(\\{(?=.*?"RKCREVZRAG_SYNTF":)(?=.*?"FGF":(\\q{5,})\\o|)(?=.*?"QNGNFLAP_VQ":"(.+?)"|)(?=.*?"YBTTRQ_VA":(\\j+)\\o|)(?=.*?"RBZ_IVFVGBE_QNGN":"(.+?)"|)(?=.*?"IVFVGBE_QNGN":"(.+?)"|)(?=.*?"CYNLRE_WF_HEY":"(.+?)"|)(?=.*?"FRFFVBA_VAQRK":"(\\q)"|)'),
H);h.M=A;h.bb=A;h.Ua=A;h.H={};h.Va="(?!)";h.Wa="(?!)";h.Xa=y('\\oshapgvba\\((\\j+)\\)\\{ine\\f+(\\j+)=[^?;,]*?(?:\\.fcyvg\\.\\j+\\(\\1,|\\1\\.fcyvg\\()(?:.+?\\ovs\\f*\\(glcrbs\\f+([\\j$]+)===?(([\\j$]+)[^()]+|"haqrsvarq")\\)\\s*return\\b)?.+?\\{return\\s+(?:([\\w$]+)\\[\\d+\\]|[^();,]+?)\\+\\s*\\1\\}\\s*return\\b[^{};]+?(?:\\.join\\.\\w+\\(\\2,|\\2\\.join\\b)[^{};]+?\\}');h.Ya=y("(?<=\\oine\\f+)${3.3}=.+?(?=[;,}])");h.Za=y("(?<=\\oine\\f+)${3.5}=(([\"']).*?\\2\\.fcyvg\\(([\"']).\\3\\)|\\[(?:(?:\".*?\"|'.*?')(?:,\\s*|(?=\\])))+\\])(?=[;,])");
h.ab=y('$> *[ebyr="znva"]:abg(uvqqra) ivqrb, :fpbcr >qvi#cynlre ivqrb, lgzhfvp-cynlre ivqrb');h.cb=y("$> lgzhfvp-cynlre qvi#fbat-vzntr vzt");h.Sa=y("$<< $> :fpbcr >ivqrb +qvi >pnainf");h.eb=y("$= lg.pbasvt_.RBZ_IVFVGBE_QNGN $= lgpst.qngn_.RBZ_IVFVGBE_QNGN $= lg.pbasvt_.IVFVGBE_QNGN $= lgpst.qngn_.IVFVGBE_QNGN");h.ua=A;h.ra=":root:empty";h.ta=0;h.sa=A;h.za=A;h.Aa='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div.xw7yly9 >div >div[style]:only-child $& div >article <';h.Ca='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div:first-child >div[role="button"][aria-hidden], article[role="presentation"] $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';
h.ya='$+ article:scope, div.x1xfsgkm:scope $* main[role="main"] article, main[role="main"] >div >div.x1xfsgkm';h.Da="$= poster $< <<<<<< $> div:scope >img:first-child, div[data-instancekey] div >img:first-child $= src";h.Ba=RegExp("/(?:p|reel|reels|stories/[\\w.-]+)/([\\w-]{11}|\\d{19})(?:[/?#]|$)");h.Na=A;h.Oa=RegExp("^(?:[^/]+|player\\.vimeo\\.com/video)/(\\d{2,})");h.Ra="$| video:scope $| video";h.Pa="$> :scope >div.player";h.Qa="$& div.vp-video $& div.vp-telecine";h.hb=function(a){this.rb(-1);
this.g=a=browser.runtime.connect({name:(I?"top":"sub")+(a?":retry":"")+("file:"==location.protocol?":file":"")});this.j(-1,a,"onMessage",this.uc);this.j(-1,a,"onDisconnect",this.tc)};h.tc=function(){browser.runtime.lastError;this.rb();this.g=this.ma=null;window.__idm_init__=!1;window.__idm_connect__=null};h.uc=function(a){switch(a.shift()){case 11:this.Rb.apply(this,a);break;case 17:this.Sb.apply(this,a);break;case 12:this.Ub.apply(this,a);break;case 13:this.Lb=a.shift();break;case 14:this.Xb.apply(this,
a);break;case 15:this.Yb.apply(this,a);break;case 16:this.$b.apply(this,a);break;case 18:this.Wb.apply(this,a);break;case 19:this.Zb.apply(this,a)}};h.zc=function(a,b){var c=105<=this.J;let d=108<=this.J;switch(this.A=a){case 1:this.K=this.Tb=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Ta=RegExp(a,H);if(a=b.shift())this.M=RegExp(a);if(a=b.shift())this.bb=RegExp(a);if(a=b.shift())this.H=a.split(/[|:]/).reduce(ha,{});if(a=b.shift())this.Ua=RegExp(a);if(a=b.shift())this.Va=a;if(a=b.shift())this.Wa=
a;(a=b.shift())&&c&&(this.Xa=a);(a=b.shift())&&c&&(this.Ya=a);(a=b.shift())&&c&&(this.Za=a);(a=b.shift())&&d&&(this.$a=RegExp(a,H));(a=b.shift())&&d&&(this.ab=a);if(a=b.shift())this.Sa=a;if(a=b.shift())this.La=a;if(a=b.shift())this.ac=a;if(a=b.shift())this.eb=a;if(a=b.shift())this.bc=a;if(a=b.shift())this.cb=a;break;case 2:this.jb();this.K=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.L=a;if(a=b.shift())this.ua=RegExp(a);if(a=b.shift())this.yb=a;if(a=b.shift())this.Bb=a;b.shift();if(a=b.shift())this.wa=
a.startsWith("$")?a:`$< ${a.slice(1)} <`;if(a=b.shift())this.Cb=a;if(a=b.shift())this.xb=a.startsWith("$")?a:`$* ${a}`;if(a=b.shift())this.xa=a.startsWith("$")?a:`$< ${a.slice(1)} <`;if(a=b.shift())this.ub=a;if(a=b.shift())this.ra=a;if(a=b.shift())this.Db=a.startsWith("$")?a:`$* ${a}`;if(c=b.shift())this.ta=c;if(a=b.shift())this.zb=a;if(a=b.shift())this.sa=RegExp(a);break;case 4:this.jb();this.K=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Ma=a;if(a=b.shift())this.L=a;if(a=b.shift())this.za=RegExp(a);
if(a=b.shift())this.Hb=a;if(a=b.shift())this.Aa=a;if(a=b.shift())this.Ca=a;if(a=b.shift())this.Jb=a;if(a=b.shift())this.ya=a;if(a=b.shift())this.Eb=a;if(a=b.shift())this.Ea=a;if(a=b.shift())this.Da=a;b.shift();if(a=b.shift())this.Gb=a;if(a=b.shift())this.Ba=RegExp(a);break;case 3:if(a=b.shift())this.Na=RegExp(a);if(a=b.shift())this.Oa=RegExp(a);if(a=b.shift())this.Ra=a;if(a=b.shift())this.Pa=a;if(a=b.shift())this.Qa=a;break;case 5:this.K=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.L=a;if(a=b.shift())this.Kb=
a;break;default:this.K=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Ka=a}this.m.includes("^/")&&((b=this.Ma)?b="https?://"+b.slice(+b.startsWith("^"),-b.endsWith("$")||void 0):b=D.replaceAll(".","\\."),this.m=this.m.replaceAll("^/",`^(?:${b})?/`))};h.fa=function(a){if(this.A&&this.T(arguments))switch(this.A){case 1:this.lc(a);break;case 2:this.hc(a);break;case 4:this.ic(a);break;case 3:this.kc(a);break;case 5:this.jc(a)}};h.ba=function(a){let b=this.g;for(let c of document.getElementsByTagName("script"))!c.src&&
a.test(c.text)&&b.postMessage([34,null,-1,c.text]);b.postMessage([34,this.C()])};h.ia=function(a,b,c,d){if(this.wb&&c){let f=a instanceof Element?this.R(a):0,e=this.W,g=e.indexOf(null);0>g&&(g=e.length);e[g]=[a,b,d];this.ka(1229212981,g,f,c)}else d(a,b)};h.vc=function(a,b){var c=this.W.splice(a,1,null).shift();if(c){a=c[0];let d=c[1];c=c[2];a instanceof Element&&!document.contains(a)&&(b=void 0);c(a,d,b)}};h.yc=function(a){var b=a.data;if(Array.isArray(b)&&a.origin==D)switch(b[0]){case 1229212977:this.wb=
!0;a=btoa(K().toString().substr(2,9));b=btoa(K().toString().substr(2,9));this.ka(1229212978,this.ma,this.s,a,b,ea,this.pa,this.K,this.Tb,this.m,this.L);break;case 1229212979:this.g.postMessage([46,b[1],b[2],b[3]]);break;case 1229212980:this.g.postMessage([36,b[1],b[2]]);break;case 1229212982:this.vc(b[1],b[2])}};h.ka=function(a,b){window.postMessage(Q(arguments),"/")};h.ca=function(){let a=window.devicePixelRatio,b=document.width,c=document.body.scrollWidth;b&&c&&(a=b==c?0:b/c);return a};h.jb=function(){this.s||
(this.s=btoa(K().toString().substr(2,9)))};h.R=function(a){let b,c=a.l;c||(c=a.l=this.ma<<13|this.vb++,this.v[c]=a,(b=this.s)&&a.setAttribute(b,c));return c};h.O=function(a){let b=this.s,c=this.v;b&&a.removeAttribute(b);this.h&&(a.removeAttribute("__idm_uri__"),a.removeAttribute("__idm_obs__"));a.F&&(window.clearTimeout(a.F),a.F=null);a.D&&(a.D.disconnect(),a.D=null);this.X.unobserve(a);this.U.unobserve(a);delete c[a.l];delete c[a.o];delete c[a.i];a.l=a.o=a.i=a.I=a.S=null};h.fb=function(a,b,c,d,f){let e=
this.v,g=this.R(a);if(b||c){if(b&&e[b]||c&&e[c])return;d||=a.localName;a.o=b;a.i=c||=`${T}${d}/${b}`;b&&(e[b]=a);c&&(e[c]=a);this.h&&a.setAttribute("__idm_uri__",c)}a.D||(b=a.D=new MutationObserver(this.V.bind(this)),this.h&&a.setAttribute("__idm_obs__",1),b.observe(a,{attributes:!0,attributeFilter:["style"]}),b.observe(a.parentElement,{childList:!0}),this.X.observe(a),f&&this.U.observe(a));1==this.A&&t(a,this.La)&&(a.da=!0,a.cc=10);return g};h.G=function(a,b,c,d,f){if(b=this.fb(a,b,c,d,f))c=this.P(a),
this.g.postMessage([41,b,a.localName,a.src||a.data,a.i,a.o,c])};h.gb=function(a,b,c){if(!a.l&&b.l){this.h&&a.setAttribute("__idm_uri__",b.i);a.S=new WeakRef(b);b.S=new WeakRef(a);if(!a.D){let d=a.D=new MutationObserver(this.V.bind(this));this.h&&a.setAttribute("__idm_obs__",1);d.observe(a,{attributes:!0,attributeFilter:["style"]});d.observe(a.parentElement,{childList:!0});this.X.observe(a)}this.U.observe(a);this.U.observe(b);c&&this.sb(a,b)}};h.Fb=function(a){if(!a.l){var b=a.S;b&&((b=b.deref())?
this.sb(a,b):a.S=null)}};h.sb=function(a,b){let c=this.s,d=this.v,f=a.l=b.l,e=a.o=b.o,g=a.i=b.i;b.l=b.o=b.i=null;c&&b.removeAttribute(c);c&&a.setAttribute(c,f);d[f]=a;e&&(d[e]=a);g&&(d[g]=a)};h.Qb=function(a,b,c,d,f,e){let g,m,k,n;let p,l,r=window.getComputedStyle.bind(window);try{let v=0;k=document.activeElement;k&&L(k.localName)||(k=document.elementFromPoint(this.na,this.oa))&&!L(k.localName)&&(k=null);for(let q of document.querySelectorAll("video,audio,object,embed")){let C=q.localName,x;var w=
"object"==C||"embed"==C;if(w){let F=q.type.toLowerCase();if(F.startsWith("text/")||F.startsWith("image/"))continue;if("embed"==C&&"application/x-shockwave-flash"!=F)continue}if(q.i&&!q.da&&(f||e))if(f?f==q.o:e==q.i)g=q;else continue;else if(x=q.src||q.data)x!=a&&x!=b||(g=q);else if(!w)for(let F of q.getElementsByTagName("source"))if((x=F.src)&&(x==a||x==b)&&(g=q))break;if(g)if("cover"==r(q).objectFit)m=q,g=null;else break;if(m||k||n)continue;if(x){if((x==c||x==d)&&(n=q))continue;if("video"==C&&x.startsWith("data:audio/"))continue}let B=
q.clientWidth,z=q.clientHeight;if(!B||!z)continue;let V=q.getBoundingClientRect();if(0>=V.right+window.scrollX||0>=V.bottom+window.scrollY)continue;let W=r(q);if(q.I||"hidden"==W.visibility||"none"==W.display)"video"==C&&(l||=q);else{w=B*z;if(v<w&&1.35*B>z&&B<3*z){v=w;var u=q}p||=q}}}catch(v){}(a=g||m||k||n)?"video"!=a.localName&&"hidden"==r(a).visibility&&(a=null):a=u||p||l;a&&("embed"!=a.localName||a.clientWidth||a.clientHeight||(u=a.parentElement,"object"==u.localName&&(a=u)),this.fb(a,f,e));return a};
h.Pb=function(a,b,c){let d=null,f,e=browser.runtime.getFrameId;for(let g of document.getElementsByTagName("iframe")){let m=g.mb;null==m&&e&&(m=g.mb=e(g));if(m==a){d=g;break}else d||!(f=g.src)||f!=b&&f!=c||(d=g)}return d&&this.R(d)};h.P=function(a){let b=null;try{let c=window.getComputedStyle(a),d=a.getBoundingClientRect(),f=this.Z,e=Math.round(d.width),g=Math.round(d.height),m;if("hidden"==c.visibility&&!a.contentWindow)return e>5*g?null:!1;if(0==c.opacity||a.I)return!1;if(1==this.A&&0==a.offsetTop+
a.offsetHeight){for(let u=a;u=u.parentElement;){let v=window.getComputedStyle(u);if("block"!=v.display)break;if(0==v.opacity)return!1}d=a.parentElement.parentElement.getBoundingClientRect();f=0;"none"==c.display&&t(a,this.Sa)&&(e=Math.round(d.width),g=Math.round(d.height))}let k=Math.round(d.left)+a.clientLeft,n=Math.round(d.top)+a.clientTop;for(let u=0,v=0,q=a,C=c,x,B;f--&&"block"==C.display&&(x=q.parentElement)&&"div"==x.localName;q=x,C=B){B=window.getComputedStyle(x);u-=q.offsetLeft;v-=q.offsetTop;
if("hidden"==B.overflowX){let z=e-x.offsetWidth-u;0<u&&(e-=u,k+=u);0<z&&(e-=z);f=0}if("hidden"==B.overflowY){let z=g-x.offsetHeight-v;0<v&&(g-=v,n+=v);0<z&&(g-=z);f=0}}switch(a.localName){case "video":document.contains(a)&&(a.videoWidth||a.i||1>a.readyState&&2==a.networkState)&&(b=!1);if(15>e||10>g)return b;break;case "audio":if(1>e&&1>g)return b;m=!0}let p=document.documentElement,l=p.scrollWidth||p.clientWidth||document.body.scrollWidth,r=p.scrollHeight||p.clientHeight||document.body.scrollHeight;
if(k>=l||n>=r||m&&!k&&!n)return b;0==k&&n==-r&&e==l&&g==r&&(n=0);let w=a.cc||0;b=[k,n+w,k+e,n+g-w,this.ca()]}catch(c){}return b};h.Ib=function(a){var b=a.dc;if(b){b=document.elementsFromPoint((b.left+b.right)/2,(b.top+b.bottom)/2);for(var c,d;(c=b.shift())&&!c.isSameNode(a);){let f=window.getComputedStyle(c);if("visible"==f.visibility&&"0"!=f.opacity&&!ka(f.backgroundColor)){d=!0;break}}a.I=d}};h.C=function(){let a=I?80:90;try{var b=window.top.document.title}catch(c){}b||(b=(b=document.head.querySelector('meta[property="og:title"]'))&&
b.getAttribute("content"),a=70);b&&(b=b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," "),b=new String(b.trim()),b.src=a);return b};h.Vb=function(){if(!document.elementsFromPoint)return 0;var a=document.documentElement;let b=a.clientWidth||a.offsetWidth;a=(a.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0);let d=0,f=0,e=0;for(let m of c)if(m.offsetWidth>=b){var g=window.getComputedStyle(m);.95<=g.opacity&&(c=g.zIndex,"fixed"==g.position?(g=m.offsetHeight+m.offsetTop,
d<g&&g<a&&(d=g,f=c)):e<c&&(e=c))}f<e&&(d=0);return d};h.Rb=function(a,b,c,d,f,e,g,m,k,n,p){this.J=a;this.ma=b;if(d){this.ja=d;try{window.frameElement&&(window.frameElement.mb=d)}catch(l){}}this.lb(e);k&&(this.pa=k);f&&this.zc(f,Q(arguments,11));n&&(this.h=!0,this.s="__idm_id__",X("text/javascript",n));p&&(this.j(2,window,"message",this.yc),X("text/javascript",p));"loading"==document.readyState?this.Ha=!0:this.fa()};h.Sb=function(a){M=location.hostname.toLowerCase()+location.pathname+location.search;
this.Ia&&this.u&&(this.u=0,this.Ja=window.setTimeout(this.ha.bind(this,!1),3E3));this.fa(!0);a&&this.lb();for(let b of new Set(Z(this.v)))this.Ib(b)};h.Zb=async function(a,b,c,d,f,e){let g=new Headers,m=AbortSignal.timeout(1E7);d={method:d,headers:g,body:e,signal:m,priority:"high",cache:"force-cache"};if(f&&f.length){for(let n of f)g.append(n.name,n.value);g.has("referer")&&(d.referrer=g.get("referer"))}g.has("accept")||g.append("accept","*/*");g.append("accept",`application/vnd.t1c.int-${a}`);c=
await fa(c,d);let k;c&&200==c.status&&(0>b?(b=await c.arrayBuffer(),b=ba(b instanceof ArrayBuffer?new Uint8Array(b):b)):b=await c.text(),k=b);this.g.postMessage([45,a,k])};h.lb=function(a){if(this.T(arguments)){var b=[21,J.href,document.referrer];a&&b.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.g.postMessage(b)}};h.Xb=function(a){var b=a?this.T(arguments):1;if(0<b||0>b&&1!=this.A){b=this.C();let c=this.ca(),d=this.Vb();this.g.postMessage([24,
b,b&&b.src,c,d])}};h.$b=function(a,b,c,d,f){c||=this.Pb(b,d,f);d=(d=c&&this.v[c])&&this.P(d);this.g.postMessage([22,a,b,c,d])};h.Wb=function(a,b){let c,d,f=document.getElementsByTagName("a");for(let e of f)try{if(e.href==b){c=e.download||null;d=e.innerText.trim()||e.title||null;break}}catch(g){}this.g.postMessage([35,a,c,d])};h.Yb=function(a,b,c,d,f,e,g,m){if(this.T(arguments)){var k=[23,a,b,!1],n,p;var l=this.v;if(b)(l=l[b])||(k[3]=!0);else{l=m&&l[m]||g&&l[g];if(!l||l.da)l=this.Qb(c,d,f,e,m,g);if(l){if(this.Ka&&
(n=t(l,this.Ka)))var r=200;else if(n=l.getAttribute("operadetachedviewtitle"))r=130;k[2]=b=l.l;k[5]=l.localName;k[6]=l.src||l.data}else if(m||g)k[3]=!0;!n&&(n=this.C())&&(r=n.src,(p=la.exec(n))&&(n=p[1]));k[7]=n;k[8]=r}if(l)if(n=this.P(l),null!=n||document.contains(l)){if(k[4]=n,a&&1==this.A&&this.$)try{k[9]=window.sessionStorage.getItem(this.$)}catch(w){}}else this.O(l),k[3]=!0;this.g.postMessage(k)}};h.Ub=function(a,b,c,d){let f=d?RegExp(d,"i"):null;d=this.kb(document,f,b);let e=document.getElementsByTagName("iframe");
for(let g of e)try{let m=g.contentDocument;m&&!g.src&&R(d,this.kb(m,f,b))}catch(m){}a=[27,a,this.ja,d.length];c||(a[4]=d,a[5]=J.href,I&&(a[6]=J.href,a[7]=document.title));this.g.postMessage(a)};h.kb=function(a,b,c){let d=[],f={};var e="";let g="",m=!c,k;if(c&&(k=a.getSelection(),!k||k.isCollapsed&&!k.toString().trim()))return d;for(let p of a.getElementsByTagName("a"))if(m||k.containsNode(p,!0))try{let l=p.href;l&&!f[l]&&b.test(l)&&(f[l]=d.push([l,2,p.download||null,p.innerText.trim()||p.title]));
c&&f[l]&&(g+=p.innerText,g+="\n")}catch(l){}for(let p of a.getElementsByTagName("area"))if(m||k.containsNode(p,!0))try{let l=p.href;l&&!f[l]&&b.test(l)&&(f[l]=d.push([l,2,null,p.alt]))}catch(l){}for(let p of a.getElementsByTagName("img"))if(m||k.containsNode(p,!0))try{let l=p.src;l&&!f[l]&&b.test(l)&&(f[l]=d.push([l,3,null,`<<<=IDMTRANSMITIMGPREFIX=>>>${p.alt}`]));m&&p.onclick&&(e+=p.onclick,e+="\n")}catch(l){}if(c){if(e=k.toString()){c=this.N(g);for(var n of this.N(e))n&&!f[n]&&b.test(n)&&!c.includes(n)&&
(f[n]=d.push([n,1]))}for(let p of a.getElementsByTagName("textarea"))if(a=p.selectionStart,e=p.selectionEnd,(n=k.isCollapsed&&a<e)||k.containsNode(p,!0))try{let l=n?p.value.substring(a,e):p.value;for(let r of this.N(l))r&&!f[r]&&b.test(r)&&(f[r]=d.push([r,1]))}catch(l){}}else{for(let p of a.getElementsByTagName("iframe"))try{let l=p.src;l&&!f[l]&&b.test(l)&&(f[l]=d.push([l,4]))}catch(l){}for(let p of a.getElementsByTagName("script"))e+=p.innerText,e+="\n";if(e)for(let p of this.N(e))p&&!f[p]&&b.test(p)&&
(f[p]=d.push([p,5]))}return d};h.N=function(a){if(!this.Fa){var b="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,function(d){return this[d]}.bind({"%H":"\\w\\- -﻿","%T":"\\w\\-.+*()$!,% -﻿","%Q":"^\\s\\[\\]{}()"}));this.Fa=RegExp(b,"gi")}let c=[];for(;b=this.Fa.exec(a);)c.push(b.shift());return c};h.T=function(a){let b=this.u;b||(a=O(a&&a.callee?a:arguments),a.unshift(arguments.callee.caller),this.la.push(a));return b};
h.pb=function(a){let b;try{b=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.u=a&&b?-1:1;b&&(a=this.Ia,a||(a=this.Ia=new MutationObserver(this.ha.bind(this))),a.observe(b,{childList:!0}),this.h&&b.setAttribute("__idm_obs__",1));this.X=new ResizeObserver(this.V.bind(this));this.U=new IntersectionObserver(this.V.bind(this),{threshold:.2});this.Ha&&(this.Ha=!1,this.fa());for(let c,d=this.la;c=d.shift();)c.shift().apply(this,c)};h.V=function(a){if(this.g)for(let b of a)if(b.target.l)if(a=
b.target,a.isConnected){let c=b.isIntersecting;if(null!=c){let d=a.I;a.I=!c;a.dc=c?b.intersectionRect:null;c&&d&&this.Fb(a)}a.F&&window.clearTimeout(a.F);a.F=window.setTimeout(this.nc.bind(this,a),200)}else this.g.postMessage([23,null,a.l,!0]),this.O(a)};h.nc=function(a){if(!this.g)return this.O(a);a.F=null;let b=document.contains(a),c;if(b){if(c=this.P(a),1==this.A&&a.da)if(c){let d=t(a,this.La);d?.href&&d.href!=a.i&&this.G(a,null,d.href)}else a.i=a.o=null,b=!1}else this.O(a);this.g.postMessage([23,
null,a.l,!b,c])};h.ha=function(a){if(a)window.clearTimeout(this.Ja),this.Ja=window.setTimeout(this.ha.bind(this,!1),1E3);else{0>this.u?this.u=1:++this.u;for(let b,c=this.la;b=c.shift();)b.shift().apply(this,b)}};h.mc=function(a){var b=a.target;let c=b.localName;L(c)&&a.url&&(b=this.R(b),this.g.postMessage([25,b,c,a.url]))};h.qb=function(a){!a.repeat&&ia[a.keyCode]&&this.g.postMessage([31,a.keyCode,"keydown"==a.type])};h.qc=function(a){this.Lb&&this.g.postMessage([28]);if(0==a.button){let b=a.view.getSelection();
b?.isCollapsed&&!b.toString().trim()&&(this.B=1);this.g.postMessage([32,a.button,!0])}};h.sc=function(a){if(0==a.button){this.na=a.clientX;this.oa=a.clientY;this.g.postMessage([32,a.button,!1]);let b=a.view.getSelection();b&&this.B&&(this.B=b.isCollapsed&&!b.toString().trim()?0:2)&&this.g.postMessage([26,a.clientX,a.clientY,this.ca()])}};h.rc=function(){2==this.B&&(this.B=0)};h.pc=function(a){a=a.target;"a"==a.localName&&this.g.postMessage([39,a.hasAttribute("download"),a.href,a.download])};h.xc=
function(){this.g.postMessage([29])};h.wc=function(a){a=a.target;this.g.postMessage([30,a.innerWidth,a.innerHeight])};h.oc=function(){this.B=0;this.g.postMessage([33])};h.j=function(a,b,c,d,f){let e=O(arguments);e[3]=d.bind(this);this.Ga.push(e);0>a?(b=b[c],b.addListener.apply(b,e.slice(3))):b.addEventListener.apply(b,e.slice(2))};h.rb=function(a){let b=this.Ga;for(let c=0;c<b.length;c++){let d=b[c][0];if(a&&a!=d)continue;let f=b.splice(c--,1).pop(),e=f.splice(0,2).pop();0>d?(e=e[f.shift()],e.removeListener.apply(e,
f)):e.removeEventListener.apply(e,f)}};h.lc=function(a){this.Y&&(window.clearTimeout(this.Y),this.Y=null);var b=this.bb.exec(J.pathname+J.search);b&&this.tb(b[1]);if(!a){S=y("lbhghor");T=y("vqzef://lbhghor/");this.Z=2;this.ka(1229212983,this.bc);var c,d,f;a=0;for(var e of document.getElementsByTagName("script")){if(e.src){if(b=this.M.exec(e.src))a|=1,this.H[b[1]]?f=b[1]:c=e.src}else if(b=this.$a.exec(e.text)){a|=2;var g=b[1]&&parseInt(b[1],10);var m=b[2];var k="true"==b[3];var n=b[4]||b[5];var p=
b[7]&&parseInt(b[7],10);if(b=this.M.exec(b[6]))this.H[b[1]]?f=b[1]:d=D+b[0]}else if(this.Ta.test(e.text)){a|=4;var l=e.outerHTML}if(7==a)break}b=101<=this.J;e=105<=this.J;(a=k?m:n)?this.$=Y(a):this.ia(window,k||!b?136:138,k?this.ac:this.eb,this.Bc.bind(this));if(f||g||m||n||p||null!=k)var r={[124]:f,[118]:g,[136]:k||b?m:n,[138]:n,[143]:p,[139]:k};(c||=d)&&e?(d=new XMLHttpRequest,d.responseType="text",d.timeout=1E4,d.onreadystatechange=this.Cc.bind(this,c,r,l,d),d.open("GET",c,!0),d.send()):(r&&this.g.postMessage([37,
1,2,r]),l&&this.g.postMessage([34,this.C(),null,l]))}};h.tb=function(a,b,c){let d=!b;d&&(b=t(document.body,this.cb));let f=t(document.body,this.ab),e=!!f?.offsetWidth,g=!e&&b||f;g&&d&&this.G(g,a,null,"video");f&&b&&f!==b&&(d&&e?this.gb(b,f):this.gb(f,b,e));!f&&10>(c||=0)&&(this.Y=window.setTimeout(this.tb.bind(this,a,b,++c),500))};h.Cc=function(a,b,c,d){if(4==d.readyState){d=d.response;var f=this.M.exec(a);a=this.Ua.exec(d);var e=f&&f[1],g=a&&parseInt(a[1]||a[2],10);if(g&&(!this.H[g]||!this.H[e])){a=
[null,119,120,135,141,142];f=[null,this.Va,this.Wa,this.Xa,this.Ya,this.Za];e={[118]:g,[124]:e};let m=[];g=!0;let k=0;for(;g&&++k<f.length;){let n=f[k];1<k&&(n=n.replace(/\$\{(\d+)\.(\d+)\}/g,(p,l,r)=>m[l][r].replaceAll("$","\\$")));try{g=m[k]=RegExp(n,H).exec(d)}catch(p){g=null}}if(3<=k){for(d=1;d<a.length;d++)m[d]&&(e[a[d]]=m[d][0]);this.g.postMessage([37,1,1,e])}else 110<=this.J&&(e[140]=d,this.g.postMessage([37,1,4,e]))}b&&this.g.postMessage([37,1,2,b]);c&&this.g.postMessage([34,this.C(),null,
c])}};h.Bc=function(a,b,c){c&&(this.$=Y(c),this.g.postMessage([37,1,2,{[b]:c}]))};function Y(a){let b=0,c=6038198,d=0,f;for(f=a.length>>1;b<f;b++)c=31*c+a.charCodeAt(b)|0;for(f=a.length;b<f;b++)d=31*d+a.charCodeAt(b)|0;return c.toString(16)+d.toString(16)}h.hc=function d(b,c){b?(c&&b.shift().disconnect(),this.ga.disconnect(),this.va.disconnect(),this.qa.clear()):(this.ba(this.ua),this.ga=new MutationObserver(this.Nb.bind(this)),this.va=new MutationObserver(this.Mb.bind(this)),this.qa=new Set,this.Z=
3);if(c=this.Ab=t(document.body,this.Bb)){if(b=this.ga,b.observe(c,{childList:!0}),this.h&&c.setAttribute("__idm_obs__","P"),!this.ib(c,!0)&&(c=t(c,this.Cb))){var f=t(c,this.wa);f?(b.observe(f,{childList:!0}),this.h&&f.setAttribute("__idm_obs__","P"),b.observe(c,{childList:!0}),this.h&&c.setAttribute("__idm_obs__","P")):(b.observe(c.parentNode,{childList:!0}),this.h&&c.parentNode.setAttribute("__idm_obs__","P"))}}else!b&&(c=t(document.body,this.yb))&&(f=new MutationObserver(d.bind(this,b=[])),b.push(f),
f.observe(c,{childList:!0}),this.h&&c.setAttribute("__idm_obs__","R"))};h.ib=function(b,c){let d=this.ga,f=this.wa,e=this.xb,g=this.va,m=this.qa,k=0;for(let n of t(b,e,[]))m.has(n)||t(n,e)||(m.add(n),g.observe(n,{childList:!0,subtree:!0}),this.h&&n.setAttribute("__idm_obs__","M"),c&&(b=t(n,f))&&(k++,d.observe(b,{childList:!0}),this.h&&b.setAttribute("__idm_obs__","P")),G(n.getElementsByTagName("video"),this.aa.bind(this)));return k};h.Nb=function(b){let c=this.Ab;for(let d of b){b=d.target.isSameNode(c);
for(let f of d.addedNodes)1==f.nodeType&&this.ib(f,b)}};h.Mb=function(b){let c=this.W,d=this.xa;for(let f of b)for(let e of f.addedNodes)if(1==e.nodeType)if(b=e.getElementsByTagName("video"),b.length)G(b,this.aa.bind(this));else for(let g of c)if(g){b=g[0];let m=t(b,d);m&&m.contains(e)&&this.aa(b,!0)}};h.aa=function(b,c){if(!b.i){var d=t(b,this.xa),f=d&&t(d,this.ub);if(!f){let m=this.ra,k=this.ta,n=P.bind(["div","span","a"]),p,l,r,w,u;for(let v=d;v&&k--&&n(v.localName);v=v.parentNode){l=v;let q;var e=
v;var g=m+":scope:first-child:only-of-type";for(q=0;"<"==g[q];q++);q&&(g=g.slice(q));for(e=e.closest(g);e&&q--;e=e.parentElement);if(e)break;if((r=v.previousSibling)&&"div"==r.localName){p||=v.querySelector('div[role="slider"]');1==(u=v.querySelectorAll(m)).length?e=u[0]:(w=v.nextSibling)&&1==(u=w.querySelectorAll("ul:scope "+m)).length?e=u[0]:p&&1<(u=r.querySelectorAll(m)).length&&(e=u[u.length-1]);break}}!e&&l&&1==(u=t(l,this.Db,[])).length&&(e=u[0]);!e&&d&&(e=d.querySelector(`:scope >${m}`));e&&
(e=e.href);!e&&1==document.getElementsByTagName("video").length&&(f=this.sa.exec(J.href))&&(f=f[1])}f||e?this.G(b,f,e):c||this.ia(b,0,this.zb,this.Ob.bind(this))}};h.Ob=function(b,c,d){d&&this.G(b,d)};h.ic=function(b){!b&&(this.ba(this.za),b=t(document.body,this.Hb))&&(E(b,this.Aa,this.ec.bind(this)),E(b,this.Ca,this.ea.bind(this)),E(b,this.Jb,this.ea.bind(this)),E(document.body,this.Eb,this.ea.bind(this)))};h.nb=function(b,c,d){!c&&1==document.getElementsByTagName("video").length&&(c=this.Ba.exec(J.href))&&
(c=c[1]);this.G(b,c,d,"video",!0)};h.ec=function(b){for(let c of t(b,this.ya,[]))G(t(c,this.Ea,[]),this.ob.bind(this))};h.ea=function(b){G(t(b,this.Ea,[]),this.ob.bind(this))};h.ob=function(b){if(!b.i){var c=t(b,this.Da);c?this.nb(b,null,c):this.ia(b,0,this.Gb,this.fc.bind(this))}};h.fc=function(b,c,d){d&&this.nb(b,d)};h.kc=function(b){b||(this.ba(this.Na),(b=t(document.body,this.Pa))&&E(b,this.Qa,this.Ac.bind(this)))};h.Ac=function(b){if(b=t(b,this.Ra)){let c=this.Oa.exec(M);c&&this.G(b,c[1])}};
h.jc=function(b){if(!b){var c=t(document.body,this.Kb);c&&(b=this.C(),c=c.outerHTML,this.g.postMessage([34,b,null,c.slice(0,c.indexOf(">")+1)]))}};function X(b,c){b=document.createElement(b.startsWith("image/")?"img":"script");b.src=browser.runtime.getURL(c);b.onload=b.remove.bind(b);document.documentElement.appendChild(b)}function t(b,c,d){function f(l,r,w){for(;w&&r--;)w=w.parentElement;w&&(isNaN(l)||this.push(l),this.push(w));return w}if(!c)return d;let e,g,m,k=!0,n=d||[],p=c.split(ja);for(1==
p.length?p.unshift(">",NaN):p.shift();b&&(e=p.shift());){c=parseInt(p.shift(),10);g=p.shift().trim();for(m=1;"<"==g[g.length-m];m++);--m&&(g=g.slice(0,-m).trim());switch(e){case "<":b=N(g?b.closest(g):b,m);k=!0;break;case ">":b=N(b.querySelector(g),m);k=!0;break;case "{":b.closest(g)&&(b=null);break;case "}":b.querySelector(g)&&(b=null);break;case "|":if(g=g.endsWith(":scope")?b.closest(g):b.querySelector(g))return N(g,m);k=!1;break;case "&":b=f.call(n,c,m,b.querySelector(g));k=!1;break;case "*":b.querySelectorAll(g).forEach(f.bind(n,
c,m));k=!1;break;case "+":g=g?g.endsWith(":scope")?b.closest(g):b.querySelector(g):b;f.call(n,c,m,g);k=!1;break;case "=":if(g=b.getAttribute(g))return g;k=!1;break;case "@":if(g=b.textContent.trim())return g;k=!1}}return n.length?n:k&&b||d}function E(b,c,d,f,e,g){if(null==f){f=t(b,c,[]);g=new MutationObserver(E.bind(null,b,c,d,f));g.observe(b,{childList:!0});this.h&&b.setAttribute("__idm_watch__",1);this.h&&f.forEach(k=>k.setAttribute("__idm_watch__",1));for(var m of f)g.observe(m,{childList:!0});
f.length&&d(f.at(-1))}else for(let k of e){for(let n of k.addedNodes)if(1==n.nodeType)if(e=t(b,c,[]).slice(f.length),(m=e.at(-1))&&n.contains(m)){R(f,e);this.h&&e.forEach(p=>p.setAttribute("__idm_watch__",1));for(let p of e)g.observe(p,{childList:!0});for(let p of m.children)d(p)}else k.target.isSameNode(f.at(-1)||b)&&d(n);for(let n of k.removedNodes)if(1==n.nodeType)for(e=0;e<f.length;e++)if(n.contains(f[e])){f.splice(e);break}}}function N(b,c){for(;b&&c--;b=b.parentElement);return b}new U}!0;
